### PR TITLE
typescript-angular2 implementation

### PR DESCRIPTION
**Pull request by capJavert**
Recently I used todo mvc for personal side project. As I am mostly doing web apps in angular i was looking for angular2+ and typescript version of Todo app but did not found one. Current Angular 2 versions are either using javascript or old angular2 implementation. My goals for this implementation:

1.  Use more recent version of angular, angular-cli and typescript
2. Showcase modern angular2 application project set up and practices
3. Use angular-cli for building and packaging the app (not some webpack + tsc + anything else that was used in similar implementations of this inside this repository)

Any tips or questions welcome
Cheers

### CODE REVIEW

**Comment by whitefire0** [comment]
@capJavert what is the status of your work on this PR? The team is in the process of clearing up a backlog of inactive PRs.

**Comment by capJavert** [comment]
@whitefire0 I was waiting for some response from you guys? Any tips on what to do so we can merge this?

**Comment by whitefire0** [comment]
@capJavert There is an existing Angular + TypeScript implementation available in the respository, although it stands at Angular v1.3. There are currently problems with the testing suite which makes it difficult to check for full equivalence of submitted applications. The requirements for acceptance are currently being revised, so one of the maintainers will get back to you here as soon as we have a better idea as to how things are going to be specified. I take it that, as far as you know, this meets the application spec and application behaviour?

**Comment by capJavert** [comment]
@whitefire0 Yes as far as I know this meets the application spec and behaviour. When someone gets back to me I would even be willing to update to latest angular 5.x version.

**Comment by FadySamirSadek** [comment]
@capJavert Thank you so much for this PR.
As you mentioned the current example we have is using angular 1.x and has not been updated for a very long time. So I think it will be very beneficial to have an updated version, one that uses the latest Angular 6. I think it will be better to close this PR and open a new one for Angular 6, anyways if you need any help I can work with you to hopefully land this soon. 🎉

**Comment by FadySamirSadek** [comment]
> as far as I know this meets the application spec and behaviour
I think doing a rebase will tell us if the current implementation fits the specs as the old tests are broke but we now have a new test suite built with cypress that you can use to test your implementation and for us to know that all the examples are working and following the specs.

**Pull request closed without merging**
