### PR TITLE
Highlight issue counts for each framework implementation

### PR DESCRIPTION
**Pull request by ColinEberhardt**
**NOT READY TO MERGE**

I think we have a small problem at the moment where the issues for a given ToDoMVC implementation are not terrible visible. If they were highlighted more clearly I am sure it would make it more likely for framework 'advocates' to come forward and fix them.

My proposal is to add some form of issue count to the 'learn' section.

I have very much hacked a quick example together. You can see it live just for 'olives' here:

http://colineberhardt.github.io/todomvc/examples/olives/

screen shot 2014-10-16 at 22 51 42

@tastejs/owners - what do you think? Is this worth pursuing further?

### CODE REVIEW

**Comment by samccone** [comment]
@ColinEberhardt could you fast forward this sucker?

**Comment by arthurvr** [comment]
I am personally :-1: on this. I feel like it doesn't add much value for users, and can even we misleading. 

This is never gonna be neutral IMO. Seeing 2 issues could mean real issues with the implementation but might as well mean 2 open PRs (which is a sign of good maintainance). Also an issue can be something like a typo but might as well be a totally broken app :/

**Comment by arthurvr** [comment]
@ColinEberhardt you'll need to re-open this PR against master, not `gh-pages`.

**Comment by ColinEberhardt** [comment]
@arthurvr - happy to fast forwards and re-apply on master, although I thought you gave it the :-1: ?

**Comment by arthurvr** [comment]
> happy to fast forward and re-apply on master, although I thought you gave it the :-1: ?

I did but I seem to alone in that?

**Comment by arthurvr** [comment]
> happy to fast forward and re-apply on master, although I thought you gave it the :-1: ?

I personally am still :-1: but what does the rest think?

**Comment by sindresorhus** [comment]
I've redecided. I don't think it's of any benefit. Issue count is like LOCs.

**Comment by stephenplusplus** [comment]
I think it's a cool way for people interested in contributing to todomvc to
jump in, but probably not a necessary place for a shortcut. The gh issues
page + labels does a fine job.

**Comment by arthurvr** [comment]
Sam said he was :-1: as well so I'm going to close this one. Feel free to reopen if anyone disagrees.

**Pull request closed without merging**
