### PR TITLE
Angular 2 refactor

### PR DESCRIPTION
**Pull request by ColinEberhardt**
This is a continuation of #1557 - I thought I'd open this one now just to show the next steps. I'm happy to focus the review effort on #1557 then rebase these changes on top of any further updates required.

Here's a quick summary of changes:

 + Removes dependency on uuid and store.js - I don't think either were adding much value. Also, by removing them we no longer have to mess around with external type definitions (woo hoo!)
 + Moved to a more conventional Angular 2 structure (as per [this comment](https://github.com/tastejs/todomvc/pull/1557#commitcomment-15104644)) - not quite the same as the structure of angular-cli, but closer. I was also conscious that the structure should mirror other todomvc implementations.
 + Applied some code style changes, new lines between functions, etc ...
 + Made more use of TypeScript
   - No implicit any, ensure everything is typed
   - Using private access modifier
   - Property getter / setters
 + Using two-way binding to remove the need to reference the DOM from the component source
 + Using Angular 2 dependency injection to supply the store
 + Added myself as an author ;-)

### CODE REVIEW

**Comment by samccone** [comment]
Look like CI is really not happy with this changeset
https://travis-ci.org/tastejs/todomvc/builds/98277129#L1936

**Comment by ColinEberhardt** [comment]
> Look like CI is really not happy with this changeset

I don't think CI has ever been happy with the Angular 2 app ;-) - anyhow, that's just making excuses :-P -  I'll see if I can fix the tests.

**Comment by samccone** [comment]
@ColinEberhardt mind rebasing off of master :)

**Comment by ColinEberhardt** [comment]
@samccone rebased :-)

I'm struggling with the tests, webdriverjs really isn't working too well with Angular 2. This is what it looks like when `sendKeys` send the text 'buy some cheese':

screen shot 2015-12-31 at 17 54 36

I've never seen anything like it before!

**Comment by ColinEberhardt** [comment]
On another note, I've implemented routing, so the Angular 2 implementation is pretty much complete :-)

**Comment by samccone** [comment]
@ColinEberhardt looks like a similar issue here
https://travis-ci.org/tastejs/todomvc/builds/99556800

I wonder if this is a chrome + webdriver regression :crying_cat_face:

**Comment by ColinEberhardt** [comment]
Hi @samccone 

> I wonder if this is a chrome + webdriver regression

No, it appears to be a very peculiar Angular2 + webdriver issue. I've been battling with it for the past hour, trying to narrow down the problem to find the root cause, although it is evading me :-(

I've opened an issue with Angular 2 https://github.com/angular/angular/issues/6250

**Comment by ColinEberhardt** [comment]
@samccone the issue I raised regarding webdriverjs has been scheduled for the Angular 2.0 beta #2 milestone. It might take a while to resolve.

As the current TodoMVC Angular 2 implementation is currently in a state where it cannot be automation tested would you mind reviewing this PR in its present form?

It would be good to merge these changes (turning a blind eye to CI!)

**Comment by samccone** [comment]
Totally will review :)

**Comment by samccone** [comment]
(this LGTM ... to be clear this has no routing atm correct?)

**Comment by samccone** [comment]
:ship: :anchor: 

landed ... thanks @ColinEberhardt :)

**Pull request closed without merging**
