### PR TITLE
Firebrick JS MVC/MVVM Framework Example

### PR DESCRIPTION
**Pull request by smasala**
This pull request is for the addition of [Firebrick JS](http://firebrickjs.com)

## Learning Firebrick JS

The [Firebrick JS website](http://firebrickjs.com) resources and demos to get started

Here are some links you may find helpful:

* [Documentation](http://firebrickjs.com/documentation)
* [Live examples](http://sandbox.firebrickjs.com)
* [Showcase | Kitchen Sink](http://firebrickjs.com/components)

### CODE REVIEW

**Comment by smasala** [comment]
The CI checks are failing because of timing issues due to asynchronous actions.

**Comment by smasala** [comment]
TodoMVC - firebrickjs
        When page is initially opened
      V should focus on the todo input field (46ms)
    No Todos
      V should hide #main and #footer (171ms)
    New Todo
      V should allow me to add todo items (625ms)
      V should clear text input field when an item is added (
      V should append new items to the bottom of the list (51
      V should trim text input (281ms)
      V should show #main and #footer when items added (280ms
    Mark all as completed
      V should allow me to mark all items as completed (218ms
      V should allow me to clear the completion state of all
      V complete all checkbox should update state when items
    Item
      V should allow me to mark items as complete (578ms)
      V should allow me to un-mark items as complete (515ms)
      V should allow me to edit an item (858ms)
    Editing
      V should hide other controls when editing (468ms)
      V should save edits on enter (858ms)
      V should save edits on blur (1032ms)
      V should trim entered text (827ms)
      V should remove the item if an empty text string was en
      V should cancel edits on escape (843ms)
    Counter
      V should display the current number of todo items (364m
    Clear completed button
      V should display the correct text (124ms)
      V should remove completed items when clicked (329ms)
      V should be hidden when there are no items that are com
    Persistence
      V should persist its data (2168ms)
    Routing
      V should allow me to display active items (391ms)
      V should respect the back button (5289ms)
      V should allow me to display completed items (328ms)
      V should allow me to display all items (609ms)
      V should highlight the currently applied filter (265ms)
    
      29 passing (2m)

**Comment by smasala** [comment]
So that this framework amongst others pass the unit tests: https://github.com/tastejs/todomvc/pull/1400

**Comment by smasala** [comment]
Live preview http://todo.firebrickjs.com

**Comment by arthurvr** [comment]
Hey there, we had a quick chat about this and decided that we don't want to add an example for this atm, as there's still nearly no userbase and the framework and the community around it still has to mature. Feel free to ping us about this later on and we can always reconsider it. Thanks for the suggestion!

**Comment by smasala** [comment]
That's understandable. Thanks for your time and looking into it though :+1:

**Pull request closed without merging**
