### PR TITLE
New formatter on all dart code

### PR DESCRIPTION
**Pull request by MathieuLorber**
Following https://github.com/tastejs/todomvc/pull/1206

I used the commandline (fresh new) dart formatter with default configuration. It may not follow the todomvc guidelines (tab indentation for instance), but as it's not JS code I suppose it's better to follow the language rules (?).

I did not modify the resulting output. I was hesitant about maps instantiations in one line - but it's so simpler to keep the formatter output.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sure, we can bend the rules for compile to stuff.

Can you fix the merge conflict?

**Comment by MathieuLorber** [comment]
Yes I forgot to get the merge of #1206 first, but now I'm wondering if we haven't a problem... Former PR were on gh-pages, but it seems everything happens on master now. I made #1206 on gh-pages, and you merged the PR on it. Should we repair that first ?

**Comment by sindresorhus** [comment]
@MathieuLorber Oh, I missed that. Fixed now.

**Comment by MathieuLorber** [comment]
Well, I can't change the target branch here, it's simpler to close the PR.

**Pull request closed without merging**
