### PR TITLE
TodoMVC implementation for Haxe+Mithril+DCI.

### PR DESCRIPTION
**Pull request by ciscoheat**
Following up on #1551, here's a quite special version of TodoMVC. It uses the [Haxe](http://haxe.org) as language, [Mithril](http://mithril.js.org/) as web framework, and most importantly, [DCI](http://fulloo.info/doku.php?id=faq) as system architecture.

It also uses MVC practices coming directly from Trygve Reenskaug, the MVC author, summarized in the article [Rediscovering MVC](https://github.com/ciscoheat/mithril-hx/wiki/Rediscovering-MVC), where one of the most important points is that any object can be a combination of M, V and C.

I hope I have managed to make it simple and understandable, even though DCI is a new paradigm and could be a bit tricky to comprehend in the beginning. Please let me know what you think.

### CODE REVIEW

**Comment by samccone** [comment]
@ciscoheat mind rebasing off of master real quick?

**Comment by ciscoheat** [comment]
Ok, I think it's done now. It got a little bit messy.

**Comment by samccone** [comment]
@ciscoheat looks like some lint errors to fixup

**Comment by ciscoheat** [comment]
The output is compiled from Haxe to js, and uses source maps. Is linting still as issue in this case?

**Comment by samccone** [comment]
@ciscoheat can you add the files to exclude to our .jscsrc file into the root of the repo?

**Comment by ciscoheat** [comment]
No problem, thanks for your help. :)

**Comment by ciscoheat** [comment]
@samccone this implementation requires an http server, could that be why the tests are failing?

**Comment by ciscoheat** [comment]
@samccone how's it going with this? Anything I can do to help?

**Comment by samccone** [comment]
I will take a look soon 😁 ... Real job world has been keeping me a little busy this week 🙃

**Comment by ciscoheat** [comment]
Ok no worries, almost same for me but [AGDQ 2016](https://gamesdonequick.com/schedule) instead. :) Just let me know if I can do anything to help.

**Pull request closed without merging**
