### PR TITLE
Backbone app-view.js

### PR DESCRIPTION
**Pull request by elie29**
The global checkbox should be unchecked when todos are empty

### CODE REVIEW

**Comment by sindresorhus** [comment]
:+1: but please include a proper commit and PR title.

**Comment by arthurvr** [comment]
Could you swap out the first commit? (as we discussed, it's not needed)

**Comment by elie29** [comment]
I am working on github directly, how could I swap it? Thank you!

**Comment by samccone** [comment]
Same as 
https://github.com/tastejs/todomvc/pull/1231#issuecomment-90649514

**Comment by elie29** [comment]
Ok no problem. Thank you. By the way I am Elie not elia :)

Envoyé depuis mon HTC

----- Reply message -----
De : "Sam Saccone" <notifications@github.com>
Pour : "tastejs/todomvc" <todomvc@noreply.github.com>
Cc : "Elie NEHME" <elie29@gmail.com>
Objet : [todomvc] Backbone app-view.js (#1229)
Date : mar., avr. 7, 2015 19:10
Closed #1229.

&mdash;

**Pull request closed without merging**
