### PR TITLE
Drop `require.js` apps

### PR DESCRIPTION
**Pull request by arthurvr**
Looks like we're all alright with this: https://github.com/tastejs/todomvc/issues/1216.

Fixes https://github.com/tastejs/todomvc/issues/1216

### CODE REVIEW

**Comment by addyosmani** [comment]
I'm -1 on dropping these implementations, but would be open to considering given more data. I do appreciate the conversation around this being started though. Thanks @arthurvr :)

Some questions:

* When was the last time the above implementations were updated?
* How difficult have we found it to get these implementations updated after having the main, non RJS version updated?
* How do the analytics usage stats for these apps compare to the others in the collection?

**Comment by arthurvr** [comment]
> I'm -1 on dropping these implementations given AMD is still heavily used by those who haven't switched to CJS or ES6.

Still, I personally don't think the specific AMD examples add many value. People that are used to using AMD don't need examples on how to use it anymore, IMHO. If they're wanting to explore a new framework, I don't think it adds much value for them to see it written using AMD.

> When was the last time the above implementations were updated?

For all of them I think we can state the activity is fairly (/really) low. These get outdated with the 'main' example way to quick, which is a result of the duplicating we're doing.

* `canjs_require`: https://github.com/tastejs/todomvc/commits/master/examples/canjs_require
* `backbone_require`: https://github.com/tastejs/todomvc/commits/master/examples/backbone_require
* `angularjs_require`: https://github.com/tastejs/todomvc/commits/master/examples/angularjs_require
* `emberjs_require`: https://github.com/tastejs/todomvc/commits/master/examples/emberjs_require
* `knockoutjs_require`: https://github.com/tastejs/todomvc/commits/master/examples/knockoutjs_require
* `somajs_require`: https://github.com/tastejs/todomvc/commits/master/examples/somajs_require

> How difficult have we found it to get these implementations updated after having the main, non RJS version updated?

Hard, I guess. The amount [of known issues with those](https://github.com/tastejs/todomvc/pull/1220/files#diff-8b25e71f0d3d34cd7c1fe864bf1f6ded) is quite big.

**Comment by passy** [comment]
We've had a pretty long discussion about this for the AngularJS example and decided to provide one because there was a pretty substantial need from the community for a reference implementation.

That example is in fact still our 8th most popular example. So I'm definitely :-1: for on this, for now. I think we all agree that it would be nice in the long run to remove these.

screenshot from 2015-03-19 20 59 52

**Comment by addyosmani** [comment]
I agree that in the long term we should definitely seek to drop. I'd actually far prefer to see Browserify or ES6 examples at some point, but for now, I think it makes sense to keep them around.

**Comment by arthurvr** [comment]
The analytics convinced me, though I guess for the other examples it does make less sense to have this duplicative implementations. Closing for now.

**Pull request closed without merging**
