### PR TITLE
Remove completed count from first apps

### PR DESCRIPTION
**Pull request by arthurvr**
See https://github.com/tastejs/todomvc/issues/1234. Updates the tests and changes the first apps.

### CODE REVIEW

**Comment by addyosmani** [comment]
These will require some manual testing, but otherwise code changes here LGTM.

**Comment by arthurvr** [comment]
> These will require some manual testing, but otherwise code changes here LGTM.

@addyosmani Thanks Addy. I tested everything manually but if there's somebody else who wants to give this a test drive? I'd love to land these as then when I start pinging app authors into the issue I can reference to examples.

**Comment by samccone** [comment]
:+1: :clap:

**Comment by arthurvr** [comment]
@tastejs/todomvc Some other pair of eyes? Quite pressing as it's broken in firefox atm.

**Comment by arthurvr** [comment]
ping? We ready to land this one?

**Comment by samccone** [comment]
yeah I think so, will want to update the tests also correct?

**Comment by arthurvr** [comment]
> yeah I think so, will want to update the tests also correct?

That's the first commit I did ^

**Comment by samccone** [comment]
yap yap :+1:

**Pull request merged**
