### PR TITLE
Udash Framework

### PR DESCRIPTION
**Pull request by Starzu**
[Udash](http://udash.io/) is a scala.js based reactive web framework. It provides features like:
- data bindings
- type-safe RPC and REST
- type-safe UI components based on Twitter Bootstrap 
- frontend routing
- applications generator
### Links
- [Homepage](http://udash.io/)
- [Developer's Guide](http://guide.udash.io/)
- [GitHub](https://github.com/UdashFramework/udash-core)
- [Gitter](https://gitter.im/UdashFramework/udash-core)

### CODE REVIEW

**Comment by Starzu** [comment]
@tastejs Anybody here?

**Comment by addyosmani** [comment]
@Starzu Pardon the delay and thanks for the PR!

My take is that Udash is new enough that it's worth adding the implementation to our wiki for reference, but not merging directly into master until it has more traction and a slightly larger community around it. There's a maintenance overhead for each addition we add when it comes to keeping it up-to-date/inline with spec/bug-free. 

cc @arthurvr for his take.

**Comment by arthurvr** [comment]
Thanks for the PR! And yeah, sorry for the late response! I agree with Addy here, let's wait a bit. Just ping us in this issue a little later when you feel like this is ready to be re-evaluated.

**Comment by Starzu** [comment]
@addyosmani @arthurvr Hello, I think it's time to reconsider this PR. I'm not sure why GitHub doesn't want to show [the updated commit](https://github.com/Starzu/todomvc/commit/632a4633ac203465210230292b18604023bc9f0b) here - probably you have to reopen the PR.

**Pull request closed without merging**
