### PR TITLE
Elm Example

### PR DESCRIPTION
**Pull request by passy**
**Early stage, keep your fingers away from that merge button!**

I tried bringing the [elm-todomvc](https://github.com/evancz/elm-todomvc) a bit closer to our spec and would like us to consider including it as official example.

Before I go on with that, I'd like to get @evancz's okay for this, though. :)

Eating our own dogfood here:

## Why Elm?

[A functional reactive language for interactive applications.](http://elm-lang.org/) I'm personally really excited about this, because it doesn't just incrementally tries to improve things, but actually rethink the entire platform from the ground up. This enables some things that are pretty much unheard of in the vanilla JS world, like a [time-travelling debugger](http://debug.elm-lang.org/) and a highly interactive development workflow with [hot code swapping](http://elm-lang.org/blog/Interactive-Programming.elm).

The project has been around for a while and is still [super active](https://github.com/elm-lang/Elm). There are a couple of TodoMVC implementations floating around, but this one is especially interesting because it brings the virtual DOM ideas to Elm. Here's a nice article describing this in depth: http://elm-lang.org/blog/Blazing-Fast-Html.elm

## Outstanding Issues

The layout is a bit buggered right now, I'm not quite sure why. I need to read a bit about Elm's full screen rendering mode. I also haven't run the test suite yet. I'm sure there'll be a couple of edge-cases that haven't been covered yet.

### CODE REVIEW

**Comment by evancz** [comment]
I just updated the code for 0.14.1 which allows `Html` values to flow through `main`. This resolves the issue with scrolling when there are a bunch of tasks, and I could imagine it fixes the centering thing you describe. Can you let me know?

The flakiness may be due to how `focus` works right now. Does that sound plausible?

**Comment by rtfeldman** [comment]
@passy I'd love to see this get merged...anything I can do to help? Is the "snapping into position after interaction" the only remaining issue?

**Comment by passy** [comment]
@rtfeldman Thanks for the offer! I'm going to try to bring @evancz's changes back into this branch. If the snapping issue should still be there, I'll give you a shout. :)

**Comment by addyosmani** [comment]
@passy Appreciate you working on bringing the 0.14.1 changes back in. Do let me know if/when you need help testing.

**Comment by passy** [comment]
@addyosmani Just in time! I pushed a rebased, updated version just a second ago. Will run the test suite against it now, but it looks pretty awesome to me.

**Comment by passy** [comment]
Test suite is still flaky, but I think it's fine. Tested the failures manually and all of them were okay. But looking at the stack traces it's pretty obvious that we expect synchronous behavior whereby Elm batches operations with the next vsync. We should certainly not punish using the correct approach here. :)

screenshot 2015-02-21 14 00 01

**Comment by addyosmani** [comment]
Hah! Indeed we shouldn't. Trying this out shortly. Nice work :)

**Comment by addyosmani** [comment]
Manually testing the elm branch, I wasn't able to find anything out of place. Tests are (as you mention) still flaking out. Is it worth adding a note about the test failures if we believe the failures are due to our own synchrony expectations?

**Comment by passy** [comment]
@addyosmani Yup, going to add them to the blacklist. There are a few which unfortunately don't pass. This one is for a good reason, though. :)

**Comment by addyosmani** [comment]
Merged away. Please feel free to add the entry to the blacklist whenever suits :)

**Comment by rtfeldman** [comment]
Awesome! Thanks so much for making this happen @passy! :smiley_cat:

**Comment by passy** [comment]
@rtfeldman I just juggled some commits around, all the hard work was done by @evancz. :smiley:

**Comment by evancz** [comment]
Just wanted to chime in and say thanks to @passy as well, I'm super excited to see Elm on the site! :)

**Pull request merged**
