### PR TITLE
Blazor 

### PR DESCRIPTION
**Pull request by TheJoeIaut**
Hi,

I implmented the TodoMVC App with ASP .NET Blazor (part of [https://github.com/dotnet/aspnetcore](ASP.NET Core)). 

Blazor allows .NET Developers to develop SPAs using C# and Razor Components. There are two different Parts to Blazor.

- Blazor Server Side: Simmilar to ASP.NET, the Views are rendered on a Server.
- Blazor Client Side: The whole Code is compiled to WebAssembly (wasm) JavaScirpt Byte Code

My implmentation uses the ClientSide Portion of the Blazor Framework.

The App is native Blazor with 2 Exceptions where no current native way exists:

- A function to Focus an elment
- A library to access the LocalStorage

The example consists of the compiled Application and the Visual Studio Project.

Test results:

(1 of 30) pass: TodoMVC - blazor, When page is initially opened, should focus on the todo input field
(2 of 30) pass: TodoMVC - blazor, No Todos, should hide #main and #footer
(3 of 30) pass: TodoMVC - blazor, New Todo, should allow me to add todo items
(4 of 30) pass: TodoMVC - blazor, New Todo, should clear text input field when an item is added
(5 of 30) pass: TodoMVC - blazor, New Todo, should append new items to the bottom of the list
(6 of 30) pass: TodoMVC - blazor, New Todo, should trim text input
(7 of 30) pass: TodoMVC - blazor, New Todo, should show #main and #footer when items added
(8 of 30) pass: TodoMVC - blazor, Mark all as completed, should allow me to mark all items as completed
(9 of 30) pass: TodoMVC - blazor, Mark all as completed, should correctly update the complete all checked state
(10 of 30) pass: TodoMVC - blazor, Mark all as completed, should allow me to clear the completion state of all items
(11 of 30) pass: TodoMVC - blazor, Mark all as completed, complete all checkbox should update state when items are completed / cleared
(12 of 30) pass: TodoMVC - blazor, Item, should allow me to mark items as complete
(13 of 30) pass: TodoMVC - blazor, Item, should allow me to un-mark items as complete
(14 of 30) pass: TodoMVC - blazor, Editing, should focus the input
(15 of 30) pass: TodoMVC - blazor, Editing, should hide other controls when editing
(16 of 30) pass: TodoMVC - blazor, Editing, should save edits on enter
(17 of 30) pass: TodoMVC - blazor, Editing, should save edits on blur
(18 of 30) pass: TodoMVC - blazor, Editing, should trim entered text
(19 of 30) pass: TodoMVC - blazor, Editing, should remove the item if an empty text string was entered
(20 of 30) pass: TodoMVC - blazor, Editing, should cancel edits on escape
(21 of 30) pass: TodoMVC - blazor, Counter, should display the current number of todo items
(22 of 30) pass: TodoMVC - blazor, Clear completed button, should display the correct text
(23 of 30) pass: TodoMVC - blazor, Clear completed button, should remove completed items when clicked
(24 of 30) pass: TodoMVC - blazor, Clear completed button, should be hidden when there are no items that are completed
(25 of 30) pass: TodoMVC - blazor, Persistence, should persist its data
(26 of 30) pass: TodoMVC - blazor, Routing, should allow me to display active items
(27 of 30) new issue: TodoMVC - blazor, Routing, should respect the back button
(28 of 30) pass: TodoMVC - blazor, Routing, should allow me to display completed items
(29 of 30) pass: TodoMVC - blazor, Routing, should allow me to display all items
(30 of 30) pass: TodoMVC - blazor, Routing, should highlight the currently applied filter
passed: 29/30
failed: 1/30

The 1 failed test does work when run standalone though.

Please feel Free to Add any Input or Suggestions.

### CODE REVIEW

**Comment by Mflameisaac** [comment]
Hi just discovered something (great work on blazor by the way by the way awesome). when you create a folder within pages called settings .in that directory you create a folder called system then create a blazor file called settings . the program will fail to compile cause the compiler will reference the user programs namespace instead of Microsoft for the using system namespace

**Comment by TheJoeIaut** [comment]
> Hi just discovered something (great work on blazor by the way by the way awesome). when you create a folder within pages called settings .in that directory you create a folder called system then create a blazor file called settings . the program will fail to compile cause the compiler will reference the user programs namespace instead of Microsoft for the using system namespace

Hey, i am not sure if i understand your suggestion correctly. Is this an issue with my code or a general Blazor problem?

**Comment by ngbrown** [comment]
Is there a live demo of this? Can this be updated to .NET 5?

**Comment by TheJoeIaut** [comment]
> Is there a live demo of this? Can this be updated to .NET

The is no live DEMO atm.

It can be ported to .NET 5 without any Problems. I may update it son.

**Pull request closed without merging**
