### PR TITLE
Update to Firebase 2.2.2 and AngularFire 1.0.0

### LINKED ISSUE #1102: Upgrade Angular+Firebase Example to latest version of Firebase + AngularFire
The current version of the Angular+Firebase example is on AngularFire 0.5.0 while the current version is 0.9.0. There have been many changes to the API since that release so the example isn't very useful it its current state. 

I'd like to get it updated to latest version if that's alright with you guys.

### PR DESCRIPTION
**Pull request by davideast**
Fixes #1102 

The current example is on much older versions of Firebase.js and AngularFire. This PR brings the example up to date.

**examples/firebase-angular/bower.json**
- Updated Firebase to 2.1.0
- Updated AngularFire to 0.9.0

**examples/firebase-angular/index.html**
- Refactored bindings to pass todo object instead of id/index. 
- The controller methods used array notation (`$scope.todos[id]`) to grab the item from the array. The new Synchronized Array can process the todo items bound in the ng-repeat binding.

**examples/firebase-angular/js/controllers/todoCtrl.js**
- Changed path to save todos from root to `/todos`. While trivial, this demonstrates saving data to different locations.
- AngularFire has a Synchronized Array with a `forEach` method for iterations. This replaces the old `$getIndex` method.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks :)

Please only include files that are needed for running the app (eg. exclude files like dotfiles, readme, etc in dependencies).

Also make sure the [test suite](https://github.com/tastejs/todomvc/tree/master/browser-tests) is passing.

**Comment by davideast** [comment]
Gotcha!

Thought it was weird that the dependencies were included in the example. But I guess you have a build process that automates that.

**Comment by sindresorhus** [comment]
No dependencies should be included, just exclude all the junk except for the JS files needed.

**Comment by davideast** [comment]
Should I run the tests for all of the examples or just the firebase-angular tests?

I ask that because there are no firebase-angular tests.

**Comment by sindresorhus** [comment]
:arrow_up: @ColinEberhardt

**Comment by ColinEberhardt** [comment]
@davideast all the ToDoMVC implementations create the same application, therefore they share exactly the same tests. You only need to run the tests suite targeting firebase-angular, as [described here](https://github.com/tastejs/todomvc/tree/master/browser-tests#running-the-tests)

If firebase-angular does not rigidly adhere to the application specification, in that the DOM it produces is not an exact match, you do have the option of running in [lax mode](https://github.com/tastejs/todomvc/tree/master/browser-tests#lax-mode).

If you encounter any problems, give me a shout.

**Comment by davideast** [comment]
Thanks for the info @ColinEberhardt.

I ran the command below but it returned back that the `firebase-angular` implementation is unsupported. In [`allTests.js`](https://github.com/tastejs/todomvc/blob/master/browser-tests/allTests.js#L16) this project is listed in the `excludedFrameworks` array.

```bash
mocha allTests.js --no-timeouts --reporter spec --browser=phantomjs --framework=firebase-angular

You have either requested an unknown or an un-supported framework

  0 passing (0ms)

```

**Comment by ColinEberhardt** [comment]
Ah, good point. It was excluded because it is one of the few implementations that requires a hosted back-end. The test suite is designed so that eventually (hopefully!) it can be used for CI. Unless we have a build that deploys and hosts the required back-ends, we cannot add Firebase, Meteor or SocketStream to the acceptance tests.

Just remove it from the list of exclusions and give it a try!

(I must admit, I haven;t tried running the tests against the real-time solutions)

**Comment by davideast** [comment]
Hey Colin,

Thanks for the tip. I removed it from the array, but the test results were not so good. It passed two, but failed 27.

I primarily received one error:

```bash
NoSuchElementError: {"errorMessage":"Unable to find element with xpath '//input[@id=\"new-todo\"]'"...
```

I checked the HTML file and there is an input with an id of new-todo on the page. Is this a common error or perhaps something with the realtime solutions?

**Comment by ColinEberhardt** [comment]
> I primarily received one error:

This error indicates that it cannot find the `new-todo` DOM element. 

As mentioned, the tests currently do not support the hosted solutions, however, with a few tweaks I did get them working for firebase:

https://github.com/ColinEberhardt/todomvc/tree/firebase-tests

The changes I made were:

+ Change the test url from localhost to todomvc.com
+ Remove angular-firebase from the exlcuded frameworks
+ Add a great big 'sleep' after the addition of each todo item, to allow for the time it takes to persist changes.

Another issue is that the tests close the browser in order to perform a tear-down. This works because ChromeDriver does not persist local-storage, which results in all of the todo items being deleted. However, with the hosted implementations this is a problem!

The tests have a 'speed mode' where the tear down is performed via the UI, selecting all the todos then removing them. This can be initiated as follows:

    $ mocha allTests.js --no-timeouts --reporter spec --framework=firebase-angular --speedMode

With all of the changes above I was able to execute the tests!

**Comment by davideast** [comment]
Hi Colin,

Thanks for taking the time to get the tests to run. I made your fixes and this build passes 27 tests, but fails on 2 in the Routing section.

The two it fails on do work when tested manually. I'm not sure what to do to get them to pass the tests. Do you have any thoughts on this?

```bash
Routing
      ✓ should allow me to display active items (6604ms)
      ✓ should respect the back button (6939ms)
      ✓ should allow me to display completed items (6550ms)
      1) should allow me to display all items
      2) should highlight the currently applied filter
```

**Comment by davideast** [comment]
@ColinEberhardt Just pinging you about my comment above. Let me know how to proceed and I'll get it fixed.

**Comment by davideast** [comment]
Just another friendly ping @ColinEberhardt @sindresorhus :)

**Comment by samccone** [comment]
hey @davideast go ahead and update your example and I will take a look at the failing specs, just ping me when you are ready, thanks again!!

**Comment by davideast** [comment]
Thanks for the update @samccone. I updated the code to reflect the AngularFire 1.0 changes. Let me know what I need to do to merge.

**Comment by samccone** [comment]
since you are already in here, might as well update all of the dependencies to move away from bower and rather use npm.

you can follow the pattern here
https://github.com/tastejs/todomvc/commit/02be0b3abdbddebd1a9fd4a9b228f5bc9e4def74

also would you mind bumping the styles to use the new UI? You can refer to the above commit fow how to do that also.

thanks a bunch :heart: !

**Comment by davideast** [comment]
Thanks for the info! I'll get everything migrated over shortly.

**Comment by davideast** [comment]
@samccone The bower to npm migration and new style upgrade is done. Let me know if you need anything else from me.

**Comment by samccone** [comment]
hey @davideast just pulled this up, looks like you are missing quite a few files.

screen shot 2015-03-18 at 11 31 10 am
make sure to add them to

**Comment by passy** [comment]
@davideast I fixed the missing files in this branch here: https://github.com/tastejs/todomvc/tree/pr/1103

Feel free to pull in the changes to your branch.

**Comment by passy** [comment]
Never mind, the changes were small enough I just took the chance and merged it in. Thanks for the update! :)

**Comment by davideast** [comment]
You guys are awesome. Thank you so much!

**Comment by samccone** [comment]
:clap: thanks @passy you are the best :heart:

**Pull request closed without merging**
