### PR TITLE
New app - typescript-react

### PR DESCRIPTION
**Pull request by remojansen**
Hi,

I have created a typescript-react app. There are two typescript examples (backbone and angular) but working with react is quite different. Since typescript 1.6 a new type of file is available (`.tsx` instead of `.ts`). The TSX files are a typed superset of JSX files and the example showcase how to work with this kind of files. 

The example also showcases how to work with a classical object oriented approach (`SomeClass extends React.Component<IProps, IState>` instead of `React.createClass({/* ... */})`), which is more common in TypeScript apps.

Please find below the output of the unit tests.

### Tests output
```

> todomvc-browser-tests@ test /Users/remojansen/Desktop/todomvc/tests
> mocha allTests.js --no-timeouts --reporter spec --framework=typescript-react



  TodoMVC - typescript-react
    When page is initially opened

      ✓ should focus on the todo input field
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579805995,
    type: '',
    closure_uid_747125925: undefined } ]
    No Todos

      ✓ should hide #main and #footer (70ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579807716,
    type: '',
    closure_uid_747125925: undefined } ]
    New Todo

      ✓ should allow me to add todo items (607ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579809729,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579809951,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should clear text input field when an item is added (276ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579812582,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579812823,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should append new items to the bottom of the list (650ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579814623,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579814870,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should trim text input (269ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579816990,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579817226,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should show #main and #footer when items added (289ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579818987,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579819210,
    type: '',
    closure_uid_747125925: undefined } ]
    Mark all as completed

      ✓ should allow me to mark all items as completed (226ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579821528,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579821760,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should allow me to clear the completion state of all items (259ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579824050,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579824293,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ complete all checkbox should update state when items are completed / cleared (307ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579826574,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579826796,
    type: '',
    closure_uid_747125925: undefined } ]
    Item

      ✓ should allow me to mark items as complete (618ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579829138,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579829369,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should allow me to un-mark items as complete (612ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579831506,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579831732,
    type: '',
    closure_uid_747125925: undefined } ]
    Editing

      ✓ should hide other controls when editing (42ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579833889,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579834114,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should save edits on enter (605ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579836670,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579836908,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should save edits on blur (694ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579840121,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579840382,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should trim entered text (608ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579843123,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579843361,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should remove the item if an empty text string was entered (428ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579846060,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579846290,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should cancel edits on escape (501ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579848750,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579848973,
    type: '',
    closure_uid_747125925: undefined } ]
    Counter

      ✓ should display the current number of todo items (417ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579851497,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579851726,
    type: '',
    closure_uid_747125925: undefined } ]
    Clear completed button

      ✓ should display the correct text (138ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579853699,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579853924,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should remove completed items when clicked (367ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579856574,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579856806,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should be hidden when there are no items that are completed (217ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579859209,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579859451,
    type: '',
    closure_uid_747125925: undefined } ]
    Persistence

      ✓ should persist its data (1171ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579861705,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579861936,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579862613,
    type: '',
    closure_uid_747125925: undefined } ]
    Routing

      ✓ should allow me to display active items (376ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579864634,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579864860,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should respect the back button (859ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579867726,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579867944,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should allow me to display completed items (320ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579871314,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579871547,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should allow me to display all items (734ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579873860,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579874100,
    type: '',
    closure_uid_747125925: undefined } ]

      ✓ should highlight the currently applied filter (286ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444579876823,
    type: '',
    closure_uid_747125925: undefined },
  { level: { name: 'WARNING', value: 900 },
    message: 'http://localhost:8000/examples/typescript-react/node_modules/react/dist/react-with-addons.js 21628:15 Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset',
    timestamp: 1444579877052,
    type: '',
    closure_uid_747125925: undefined } ]


  28 passing (1m)


```

### CODE REVIEW

**Comment by samccone** [comment]
hi @remojansen looks like CI is complaining about your complied JS files, you can add them to the ignore here https://github.com/tastejs/todomvc/blob/master/.jscsrc#L35 and repush

**Comment by remojansen** [comment]
Hi @samccone thanks for your help. Do you need me to sync, resolve conflicts and push or you guys look after that?

**Comment by remojansen** [comment]
@samccone never mind... My branch is now on sync with master and ready to be merged.

**Comment by samccone** [comment]
@remojansen mind squashing this down into a single commit for us :)

**Comment by samccone** [comment]
no need to close @remojansen you can just force push and reopen :)

**Pull request closed without merging**
