### PR TITLE
React webpack es6

### PR DESCRIPTION
**Pull request by acamposruiz**
Hi!

Here I have develop an aproach with React 0.14 and webpack with ES6, I think can be a good thing present a way to modularize this project with webpack.

The project is in examples/react-webpack-es6.

Thanks for suggestions!

Antonio

### CODE REVIEW

**Comment by acamposruiz** [comment]
I have a problem when jshint check "examples/react-webpack-es6/build/app.js", this file is an output from webpack and I can not fix this with jshint params, I would like to know how is this managed.

Thanks!

**Comment by acamposruiz** [comment]
There is a way I could exclude "examples/react-webpack-es6/build/app.js" from jshint?

**Comment by dhruvdutt** [comment]
What's the status of this PR? @acamposruiz

**Comment by dhruvdutt** [comment]
Please clean up commit messages and rebase.

**Comment by acamposruiz** [comment]
ok, I will :)

**Comment by acamposruiz** [comment]
Hi @dhruvdutt , I will close this PR because I've a new one here: https://github.com/tastejs/todomvc/pull/1813

**Pull request closed without merging**
