### PR TITLE
Bug Fix - Issue #1405 - Problem with cancel

### PR DESCRIPTION
**Pull request by jonnykry**
This PR addresses the bug noted here: https://github.com/tastejs/todomvc/issues/1405

I simply added the suggested fix by @rulotr and it works fine!

Ran unit tests (:white_check_mark:) and tested in Firefox.

### CODE REVIEW

**Comment by samccone** [comment]
@jonnykry mind squashing your commits to be just one :)

**Comment by jonnykry** [comment]
Got it.  I had never done a rebase to squash before, TIL!

**Comment by samccone** [comment]
> Edit - is it best practice to remove the old comments and leave a comment like "issue #1405 bug fix" or something of that nature?

Yes! see :eyes:  https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by samccone** [comment]
thanks @jonnykry merged!

**Pull request closed without merging**
