### PR TITLE
jQuery example tweaks

### PR DESCRIPTION
**Pull request by dmethvin**
No ticket, let me know if you want one. I made these changes in several commits so it would be easier to see what was being done. I think the first (remove unused variables) and the last (DRY update logic) are most important but the rest are very representative of idiomatic jQuery and don't violate the MVC flavor.

### CODE REVIEW

**Comment by arthurvr** [comment]
Me likey :+1:

**Comment by sindresorhus** [comment]
:+1: Looks good to me.

**Comment by addyosmani** [comment]
LGTM 3. Thanks a lot for the clean-up, @dmethvin!

**Comment by samccone** [comment]
landed here
https://github.com/tastejs/todomvc/commit/69cb6f7c052eeb0119300375fec3dd2afdda35d9

Thanks!!!!!! :sparkles:

**Pull request closed without merging**
