### PR TITLE
Bump test specs

### PR DESCRIPTION
**Pull request by samccone**
~~* Switched to tabs in .travis.yml~~
* Updated chrome version
* Cached node_modules
* Updated selenium version
* remove unneeded chrome driver DL
* update Drool
* Remove direct call to webdriver log

### CODE REVIEW

**Comment by samccone** [comment]
odd, travis is not picking this up at all...

**Comment by sindresorhus** [comment]
> Switched to tabs in .travis.yml

You can't indent with tabs in YAML.

**Comment by tbranyen** [comment]
Nice will this fix the issues I was seeing in #1621?

**Comment by samccone** [comment]
@tbranyen this will be a good first step :)

**Comment by tbranyen** [comment]
Awesome I'll follow along. No huge rush to land the diffHTML pr, I just feel bad leaving a broken build up.

**Comment by addyosmani** [comment]
This LGTM. Nice work, @samccone :cake

**Pull request merged**
