### PR TITLE
Update to Angular2 beta.2

### PR DESCRIPTION
**Pull request by robdodson**
This seems to just work. I was able to npm install ok and boot up the app without needing to change any other bits of code. I'm not an angular expert so someone should double check the work :D

### CODE REVIEW

**Comment by samccone** [comment]
please commit the changed vendor files :)

**Comment by samccone** [comment]
and any updated dist files

**Comment by addyosmani** [comment]
Friendly ping to @robdodson about committing the updated vendor files if you get a chance :cake:

**Comment by robdodson** [comment]
oh this PR is oooold

**Comment by addyosmani** [comment]
SOOOOOO old.

**Comment by robdodson** [comment]
I suck and don't have any of this source laying around anymore. Probably better to just close this and start a new one with the latest angularz

**Pull request closed without merging**
