### PR TITLE
IE11 fix for Dojo example, fixes #1349.

### LINKED ISSUE #1349: Dojo todomvc not working in ie11
please see post on so http://stackoverflow.com/questions/30980564/dojo-todomvc-not-working-in-ie11

No errors, Not working for me on ie11, chrome is fine

### PR DESCRIPTION
**Pull request by asudoh**

### CODE REVIEW

**Comment by arthurvr** [comment]
Mind quickly explaining how this fixes a bug specific to IE11? It seems more like adding a new feature? Thanks.

**Comment by asudoh** [comment]
Not a new feature, IE11 does not fire change event on `<input>` upon parent `<form>` submission, all added code is for coping with that. Thanks.

**Comment by arthurvr** [comment]
Ugh. IE :cry: 

Tests pass, code lgtm and works fine. Neat work. Thanks!

**Comment by samccone** [comment]
woot thanks @asudoh :sparkling_heart:

**Pull request merged**
