### PR TITLE
Update stats.html

### PR DESCRIPTION
**Pull request by elie29**

### CODE REVIEW

**Comment by samccone** [comment]
:+1: again

**Comment by sindresorhus** [comment]
:+1: but please include a proper commit and PR title.

**Comment by samccone** [comment]
yeah I think @arthurvr was planning on merging all of these and formatting the commit messages

@elia would be great if you wanted to do this though, it looks like you used the web editor to do this work, so it would take a touch of git foo to fix all of this up (nothing too crazy thought)

**Comment by elie29** [comment]
@samccone do I need to commit again with a proper title and message?

**Comment by arthurvr** [comment]
Change you existing commit, you can amend it :)

**Comment by elie29** [comment]
Ok I have no connection before tomorrow. I am using my mobile actually.

2015-03-24 10:18 GMT+01:00 Arthur Verschaeve <notifications@github.com>:

**Comment by arthurvr** [comment]
https://github.com/tastejs/todomvc/pull/1228#issuecomment-85568559

**Pull request closed without merging**
