### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by elie29**
We should display the completed todos after the clear link

### CODE REVIEW

**Comment by samccone** [comment]
:+1: to escaping, not sure how this lines up with your PR message though?

**Comment by elie29** [comment]
What do you mean?

**Comment by samccone** [comment]
> We should display the completed todos after the clear link

not sure how this lines up the the change to interpolating

**Comment by elie29** [comment]
http://todomvc.com/examples/backbone/
When you check a todo, "clear completed" is displayed without the number of completed todos. But when you test with my commit, you will get the correct result : 
image

**Comment by elie29** [comment]
I should put this message : displaying the number of completed to using minus sign for HTML-escaped (cf. underscore)

**Comment by sindresorhus** [comment]
:+1: but please include a proper commit and PR title.

**Comment by arthurvr** [comment]
> I should put this message : displaying the number of completed to using minus sign for HTML-escaped (cf. underscore)

I don't know if you actually tested this, but it doesn't work. Currently this worked fine, but we were just running into https://github.com/tastejs/todomvc/issues/1215. The actual problem will get fixed when we fix todomvc-app-css, this does not fix anything.

Do we still need these PRs, then?

**Comment by elie29** [comment]
No it is not necessary :+1:

**Pull request closed without merging**
