### PR TITLE
Update readme.md to add instructions for Visual Studio 2015 RC

### PR DESCRIPTION
**Pull request by svcondor**
As per request I've added instructions for running this example under Visual Studio 2015 RC.

### CODE REVIEW

**Comment by arthurvr** [comment]
Does it make sense to have such a big explanation in that document about this? It seems like not related to comparing MVC solutions anymore.

Please also edit the PR title to be something more useful than `update readme.md`. Using this one we can't even know about what example we're talking about ;)

**Comment by svcondor** [comment]
Sorry, I’m new to GitHub, I’ve changed the PR title.

It would be better if Visual Studio had a suitable template for client-side javaScript apps.   I don’t think they can be more concise without leaving something out.   Would you prefer them in a separate .md file or just as an issue?

R, David.

**Comment by arthurvr** [comment]
Even we add something at all, I'd rather have us linking to an external resource than even having this all in the repo. This isn't helping people comparing MVC frameworks anymore, it's teaching people how to use an IDE.

**Comment by svcondor** [comment]
You’re right it’s not related to comparing MVC frameworks.   I only did it because I thought you’d asked me to.
I’ve only just realized that samccone/todomvc is a fork of tastejs/todomvc.   He asked me to do this but I did the pr on your repo by mistake.

“samccone  commented 9 hours ago
If anyone would like to open a pr and add readme docs around how to run this in visual studio it would be very welcome. Thanks @svcondor”

I’m sorry for all the confusion, I’ll delete the fork if I can work out how.

Regards, David.

**Pull request closed without merging**
