### PR TITLE
Add README to SAPUI5 example #386

### PR DESCRIPTION
**Pull request by jyguyomarch**
Adding a README file to the SAPUI5 TodoMVC example. Used the provided readme-template as a basis.

### CODE REVIEW

**Comment by passy** [comment]
Looks good to me! :+1:

**Comment by jyguyomarch** [comment]
Thx @passy

**Comment by arthurvr** [comment]
Going to wait for feedback from @akudev but this does actually look good to me.

**Comment by jyguyomarch** [comment]
Just realized that @akudev is on vacation until mid july. Not sure if he checks his github during this time. But it's only a README so we can wait for his feedback. Or just merge it and I'll make some changes later if need be.

**Comment by samccone** [comment]
manually merged in 
2de650d1e28f9b28d62d8378c2dffe165b58a07a

thanks @jyguyomarch !!!

**Comment by jyguyomarch** [comment]
Hey @samccone, not sure what "Closed with unmerged commits" means here. Can you explain if you have 2 mins? Nothing urgent.

**Pull request closed without merging**
