### PR TITLE
TodoMVC create react app es6 - <work in progress>

### PR DESCRIPTION
**Pull request by rickhallett**
PR based on #1853 

The aim is to complete work by started by jchris to bring the React TodoMVC example up to speed with the the latest release of React, the create-react-app development environment,  ES6, ReactDOM and prettier.io formatting style. This should bring the code into line with the standards that beginners are most likely to encounter when starting with React.

### CODE REVIEW

**Comment by FadySamirSadek** [comment]
@whitefire0  make sure you add the email associated to your github account to your local settings so github can show your name and github profile on the contributors list after this is merged

**Comment by whitefire0** [comment]
@FadySamirSadek Thanks for the reminder, seems I had a typo! Work is close to complete, although the react-router is proving more difficult than anticipated. I have squashed commits, and I didn't realise so many of the commits would show above!

What are the expectations regarding the travis CI build and this version of the todoMVC?

**Comment by whitefire0** [comment]
@FadySamirSadek the latest commit is my latest version: its been updated to ES6 and formatted with prettier. As it stands, I'm not experienced enough in React to figure out why the edit functionality is currently broken - my guess is that props are not being passed down properly `Cannot read property 'props' of undefined - TodoItem.js:25`, and that this is something to do with changing to a class format, use of `this` etc.. If anyone is able to help me with this that would be great, as I think this might be close to passable.

**Comment by FadySamirSadek** [comment]
@whitefire0 Exactly one of the key differences between using function and class based components is the handling of the this keyword. [There is this awesome article ](https://medium.freecodecamp.org/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56)by Cory House that explains it and different ways to handle it. Definitely recommend checking it out  ;)

**Comment by whitefire0** [comment]
@FadySamirSadek I have pushed what I think is completed work, having fixed the binding and css issues. Some of the properties changed in the media-query toggle all were creating issues with visibility/functionality. I'm not sure if these changes are acceptable so any feedback is very much appreciated!

**Comment by FadySamirSadek** [comment]
@whitefire0 can you please rebase on master to use the new cypress test suite instead of the selenium one which is broke

**Comment by whitefire0** [comment]
@FadySamirSadek I can't quite work out how to do this. Could you take a look at this git output and advise?

[](http://prntscr.com/isuo09)

**Comment by FadySamirSadek** [comment]
@whitefire0  There is a merge conflict that occurred because the code has been changed since the last time you forked TodoMVC. To solve this you will need to either solve these merge conflicts manually or use a tool like mergetool for mac there are also another tools available for windows.
You can watch [this awesome video on youtube](https://www.youtube.com/watch?v=JtIX3HJKwfo) by The coding train that explains merge conflicts and how to resolve them.

**Comment by whitefire0** [comment]
@FadySamirSadek thats great, thanks for taking the time to help. I will look into this today and get things sorted out!

**Comment by whitefire0** [comment]
@FadySamirSadek Apologies for the delay; I have not had as much time as I had anticipated. As far as I am aware, this commit contains CSS fixes, prettier formatting, conversion to ES6, conversion to create-react-app and resolution of merge conflicts since the change to the Cypress testing suite.

**Comment by whitefire0** [comment]
@FadySamirSadek I've duplicated the index.html into the root directory for now, leaving a copy in /public, as this is needed by create-react-app in the current configuration. I will look into how this can be changed, provided the testing passes.

**Comment by whitefire0** [comment]
@addyosmani apologies if this mention isn't appropriate; I believe you are another major reviewer on this project, is that correct?

**Comment by FadySamirSadek** [comment]
@whitefire0 I already started working on a guide to land this but was caught up in exams the past few days. Will work with you on the weekend to land this ;)

**Comment by whitefire0** [comment]
@FadySamirSadek that's really great - appreciate your help! Also please do point me in the direction of documentation if I can share the load in anyway; I am just not sure where to focus my reading at this point

**Comment by FadySamirSadek** [comment]
please refer to #2219

**Pull request closed without merging**
