### PR TITLE
Migrate `Aria templates` example to `todomvc-app-css`

### PR DESCRIPTION
**Pull request by arthurvr**
Next PR of mine for https://github.com/tastejs/todomvc/issues/1110. This time the Aria templates example.

* Included `todomvc-app-css`, updated the version of `todomvc-common`. This includes the new UI :tada:.
* Replaced bower by NPM.
* Include all files that aren't needed in the repo in the gitignore, as suggested by https://github.com/tastejs/todomvc/issues/1110.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Tip: You should do PRs from a new branch (not master) ;)

**Comment by sindresorhus** [comment]
Seems it's still using the old checkbox and "mark all as complete" button.

**Comment by arthurvr** [comment]
Really weird, seems like [this was hard-coded in the CSS file](https://github.com/tastejs/todomvc/blob/master/examples/ariatemplates/js/view/TodoStyle.tpl.css#L47). Any idea why?

**Comment by sindresorhus** [comment]
@arthurvr No idea. This seems good for now. Can you open an issue about getting it fixed up completely?

**Pull request merged**
