### PR TITLE
Update `react` example to use classes

### PR DESCRIPTION
**Pull request by arthurvr**
Updated the react example to the latest `todomvc-app-css`. This includes the change to use classes instead of IDs. 

@samccone Seems like all routing tests fail. Looks like a problem with the testsuite. Can you take a look?

### CODE REVIEW

**Comment by arthurvr** [comment]
@samccone Would you be able to look into this any time soon? If not we should probably just merge this one and open a separated issue about the tests.

**Comment by samccone** [comment]
yes today :dancer:

**Comment by arthurvr** [comment]
Did the react-backbone app too.

**Comment by arthurvr** [comment]
The tests are fixed. Anyone who wants to review this?

**Comment by samccone** [comment]
Mind a quick rebase off of master 📴

**Comment by arthurvr** [comment]
done.

**Comment by arthurvr** [comment]
@samccone Mind taking a look at this failure as well? :p

**Comment by samccone** [comment]
sure thing :)

**Comment by samccone** [comment]
there is one more method that is prone to flake @arthurvr  working on it `this.assertItems = function (textArray) {`

**Comment by arthurvr** [comment]
This should be good to merge, right? There are problems with the test suite not really with the app.

**Comment by arthurvr** [comment]
@samccone Did #1372 too. PR'd this one but later on I'm just going to commit the others to master.

**Pull request merged**
