### PR TITLE
Use generic comment for localStorage namespace in backbone examples

### PR DESCRIPTION
**Pull request by m90**
The comments in the backbone examples are slightly off and made me (slightly) confused when reading them.

### CODE REVIEW

**Comment by samccone** [comment]
hi @m90 would you mind squashing this down into a single commit?

Thanks a bunch!

**Comment by m90** [comment]
Umm, stupid question, but can I do this **without** merging into a new branch and then opening a new PR? If that's the way to go I'm ready!

**Comment by samccone** [comment]
oh did you use the web editor to do this¿ if so no worries we can squash manually before we merge

**Comment by m90** [comment]
Web editor, exactly. Lots of commits. I'm fine with whatever is the easiest for you.

**Comment by samccone** [comment]
All taken care of, thx for the PR :sparkles:

**Pull request closed without merging**
