### PR TITLE
Fix jscs issues found in #1403...

### PR DESCRIPTION
**Pull request by kentcdodds**
I am so sorry that this results in a bunch of whitespace change and git history nuking 💣

### CODE REVIEW

**Comment by kentcdodds** [comment]
Once this gets merged, I'll rebase it into #1403 and force push. Hopefully then it will get in. Thanks!

**Comment by samccone** [comment]
oh wow looks like this does not even pass specs either! but thanks for this!!!

**Comment by kentcdodds** [comment]
Thanks! I'll go ahead and rebase the other one and update the PR. Hopefully we can figure out why the tests are failing later.

**Comment by samccone** [comment]
:+1:

**Pull request merged**
