### PR TITLE
Remove an outdated video

### PR DESCRIPTION
**Pull request by robbbz**
This is from years ago so can be removed. I fail to find a good replacement so I removed it in commit https://github.com/tastejs/todomvc/commit/8c947f300f2794f789cd13107af13eed2bcf8483.

### CODE REVIEW

**Comment by samccone** [comment]
This is still a valuable resource imho

**Comment by mathiasbynens** [comment]
> This is still a valuable resource imho

Agreed.

**Comment by arthurvr** [comment]
Although the jQuery source itself may be outdated, it's still valuatie so I'm going to close this.

**Comment by arthurvr** [comment]
And Sam was earlier :P

**Comment by samccone** [comment]
:racehorse:

**Pull request closed without merging**
