### PR TITLE
fix checkbox bug in the mithril TodoMVC example

### PR DESCRIPTION
**Pull request by nordfjord**
The bug is caused by lack of keying.

To reproduce the bug:
1. Open the app
2. Create at least two tasks
3. Complete all tasks
4. Go to the completed view
5. uncheck the top item
6. Voilá, see how the first item in the list now has an unchecked checkbox

### CODE REVIEW

**Comment by samccone** [comment]
Thanks a ton of the PR, looks likes few lint errors on your branch. Mind taking a look?

**Comment by nordfjord** [comment]
Sure thing, I think it should be fixed now, (I squashed the commits per the pull request guidelines).

However there seems to be a test failing, which I'm going to attribute to a badly written test.
I'll get on fixing the test.
The test error says the element should be hidden, and complains that it can't be found (ringing any irony bells?)

**Comment by samccone** [comment]
Hi @nordfjord you are correct it looks like a bad assumption on the tests part

The best test is located here
https://github.com/tastejs/todomvc/blob/aeb5e7e2ce8a6a918ce6b9020156f126baae9d76/tests/testOperations.js#L30-L34

Let me know if run into any troubles fixing the test, I am more than willing to fix it, however I very much appreciate you volunteering to fix it! Thanks a ton!!!

**Comment by nordfjord** [comment]
I seem to have figured this out,

I added an error callback to the check, which then asserts the error code is 7 (7 is the error code for element not found).
and everything seemed to run dandily on my end.

I however would like to skip squashing this commit since it's completely unrelated to the other one, so I would rather like to be able to see in the commit history that both a change to mithril was made and to the tests.

Regards,
Einar

**Comment by samccone** [comment]
awesome this looks great @nordfjord awesome work :space_invader:

**Pull request merged**
