### PR TITLE
Migrate `gwt` example to `todomvc-app-css`

### PR DESCRIPTION
**Pull request by arthurvr**
* Included `todomvc-app-css`, updated the version of `todomvc-common`. This includes the new UI :tada:.
* Replaced bower by npm.
* Include all files that aren't needed in the repo in the gitignore.
* #1110

### CODE REVIEW

**Comment by sindresorhus** [comment]
It still has the old checkbox button and delete button.

**Comment by samccone** [comment]
ping ping @arthurvr :)

**Comment by samccone** [comment]
ping @arthurvr :smile:

**Comment by arthurvr** [comment]
GWT is such a pain. I'll look into it again but wasn't even able compile the app yet :p

**Comment by samccone** [comment]
ping @stephenplusplus 

it looks like you were the last warrior to compile this dragon in the hills of GWT.

**Comment by sindresorhus** [comment]
Alright. Landed. Better than existing. I've opened an issue about improving it: https://github.com/tastejs/todomvc/issues/1418

**Pull request closed without merging**
