### PR TITLE
Remove cloud9 and Codio links in the readme

### LINKED ISSUE #957: Broken codio link?
In the readme, the `edit in Codio` button seems to be broken. It throws me this 404 error: 
screenshot 2014-07-28 12 53 52

### LINKED ISSUE #1428: Is cloud9 down or todomvc workspace is not available anymore?
I'm getting a 404 error when trying to edit the code using cloud9. 
Is it down or the workspace is not available anymore?

### PR DESCRIPTION
**Pull request by arthurvr**
https://github.com/tastejs/todomvc/issues/1428#issuecomment-136405370

Fix #1428
Fix #957

### CODE REVIEW

**Comment by addyosmani** [comment]
:+1:

**Comment by pbassut** [comment]
:+1:

**Comment by samccone** [comment]
lgtm :shipit:

**Comment by arthurvr** [comment]
@samccone 

> Perhaps PR the removal and if no one says anything after a week we nix them?

20 minutes ;)

**Comment by samccone** [comment]
:rocket:

**Pull request merged**
