### PR TITLE
thorax_lumbar: Cancel editing with the Escape key

### PR DESCRIPTION
**Pull request by dmethvin**
Ref #789

In a separate commit I've fixed a bunch of jshint failures and a style indentation issue unrelated to adding the feature. I can squash these if you prefer.

### CODE REVIEW

**Comment by dmethvin** [comment]
Not sure why my jscs passed and this one did not, I thought I pulled the right .jscsrc file. I can try fixing these as well if you want.

**Comment by samccone** [comment]
seems like we might want to drop base.js from the linting eh :)

**Comment by dmethvin** [comment]
I can't get jscs (2.6.0 installed globally) to work here, it just hangs one core for at least 5 minutes before I give up. It's seeing too many errors so probably the only solution that doesn't involve a bunch of edits is to exclude the whole example from the check.

**Comment by samccone** [comment]
@dmethvin since all the files in public seem to be generated.. how do you feel about just ignoring that entire dir?

**Comment by dmethvin** [comment]
@samccone well i guess i feel pretty good about it.

**Comment by samccone** [comment]
I feel good about it as well :D

**Comment by samccone** [comment]
manually landed, thanks again @dmethvin :wink:

**Pull request closed without merging**
