### PR TITLE
Update React example

### PR DESCRIPTION
**Pull request by J-F-Liu**
This example is created using React 16.7 and styled-components.
PR for #1959.

### CODE REVIEW

**Comment by FadySamirSadek** [comment]
Thank you so much @J-F-Liu for your PR, I'll be working with you to try to ship this ASAP.
Can you please have a look at the CI issue and try to address it?
It seems that the Todo input isn't in focus when the app starts which is failing the entire test suite.
Thanks again for your PR and sorry for the late reply.

**Comment by J-F-Liu** [comment]
@FadySamirSadek Updated code, but Travis failed to start Cypress.

**Comment by karolyipeter** [comment]
Hello! I see this is still in progress, mind if I take over? I would really like a working react example since it is one of the biggest frameworks right now.

**Comment by welll** [comment]
I see this is still in progress, let me know if I can take this over.

**Pull request closed without merging**
