### PR TITLE
update projects to todomvc-app-css v2

### LINKED ISSUE #1780: gh-pages branch has not been updated
I got in a [fix](https://github.com/tastejs/todomvc-app-css/pull/8) in for [todomvc-app-css](https://github.com/tastejs/todomvc-app-css) few weeks back, and noticed it wasn't working on todomvc.com. When I checked, I saw that most of the assets in the gh-pages branch haven't been touched in [9 months](https://github.com/tastejs/todomvc/tree/385da5d55ecbb2b1b0255402577f39f08a79d6a0/examples). Since it is a separate package, they apparently need to be kicked in order to get the updated css.

How would one go about updating the site to the latest module versions?

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #1780 

upgraded (almost) all of the projects that use `todo-app-css` to the fixed v2 version, also fixed the toggle-all button being breaking in some of the layouts.

I did _not_ update `chaplin-brunch`, `foam`, or `gwt` because I couldn't figure out how their build systems worked to update the files.

### CODE REVIEW

**Comment by addyosmani** [comment]
Wow. That's one really useful first time contribution. Thanks a _lot_ for investing time in this set of changes, @patrickkettner.

**Comment by addyosmani** [comment]
Some recent changes to master appear to have caused some Travis CI breakage (I don't believe it's this PR) https://travis-ci.org/tastejs/todomvc/builds.

**Comment by patrickkettner** [comment]
no worries - let me know if there is anything I can do to help get travis fixed or this merged

**Comment by MattKotsenas** [comment]
Thanks @patrickkettner! I pull this down locally and took a look at some of the examples and they look great! @addyosmani, is there anything we can do to help get this merged? Thanks!

**Comment by FadySamirSadek** [comment]
Thanks @patrickkettner for this awesome contribution I cloned your fork and tried it out excellent job🎉
Thanks @MattKotsenas for helping with the review.

**Pull request merged**
