### PR TITLE
Update marionette.js to v3

### PR DESCRIPTION
**Pull request by denar90**
Changes: 
 - update Todo example due to v3 [release](https://github.com/marionettejs/backbone.marionette/releases/tag/v3.0.0)
 - update readme file with links to resources. Some of them were broken so new links were added.
 - replaced `MarionetteJS` by `Marionette.js` on main page.

### CODE REVIEW

**Comment by denar90** [comment]
Guys, is Travis build broken in general or it's just because of my changes?

**Comment by samccone** [comment]
@denar90 travis is broken I need to fix webdriver

**Comment by denar90** [comment]
@samccone Do you wanna webdriver be fixed before merging some PR's?

**Comment by samccone** [comment]
I just need to carve out some time to manually test his and the other outstanding open PRs.  :)

**Comment by samccone** [comment]
👍 checked manually all is well here.. landing thanks for the PR

**Comment by denar90** [comment]
Awesome 🎉  💃 Thanks! Cake on me 🍰

**Comment by addyosmani** [comment]
🍰 all around. Thanks both!

**Pull request merged**
