### PR TITLE
Drop batman example.

### PR DESCRIPTION
**Pull request by samccone**
Batman is no longer under in active development and is "sleeping"
https://github.com/batmanjs/batman#shhh-batman-is-sleeping

http://www.shopify.com/technology/15646068-rebuilding-the-shopify-admin-improving-developer-productivity-by-deleting-28-000-lines-of-javascript

### CODE REVIEW

**Comment by arthurvr** [comment]
Needs to be removed from learn.json as well.

**Comment by samccone** [comment]
gone

**Comment by arthurvr** [comment]
Thanks Sam

**Comment by passy** [comment]
Thanks!

**Pull request merged**
