### PR TITLE
Remove helper and view files from tests

### PR DESCRIPTION
**Pull request by kentcdodds**
I'm in the process of rewriting/tooling this in ES6 for a workshop I'm doing and I realized that you don't actually need either of these files for the tests to run 👍

### CODE REVIEW

**Comment by kentcdodds** [comment]
The failure appears to be related to `jscs`...

**Comment by samccone** [comment]
not super surprising since this version has not been updated in a while, any interested in resolving the issues here?

**Comment by kentcdodds** [comment]
I'm sort of looking at it now. I can give it a few minutes, but then I have to get back to the workshop. This was supposed to be quick ;-)

**Comment by samccone** [comment]
looks like jscs -x would resolve most :package:

**Comment by kentcdodds** [comment]
This will fail... :-( But I promise that I've run the tests locally (at least the ones specific to this project, which this impacts... Didn't realize that there was an overarching test suite).

**Comment by samccone** [comment]
oh yeah it is pretty sweeeeet, we are just running jscs and the test suite over the code touched by your DIFF it is super :hotsprings: stuff

**Comment by kentcdodds** [comment]
Yeah, really impressive. It's actually nice so that contributors don't have to deal with issues that come up in other implementations. Avoids:

> WTH!? What do I care about Angular? I'm contributing to the Ember version!

Good work!

**Comment by samccone** [comment]
yeah what is funny is the spec_runner in the project is not run by us. We have a suite of integration tests that we run... I will checkout the branch tomorrow and just double check

thanks again for this work 

:a: :heavy_plus_sign:

**Comment by kentcdodds** [comment]
I've always wanted to contribute to TodoMVC 👍 Have a good night/morning/afternoon ¯\_(ツ)_/¯

**Comment by samccone** [comment]
screen shot 2015-08-11 at 5 16 11 pm

:white_check_mark:

**Pull request merged**
