### PR TITLE
knockoutjs_require: Cancel edits using Escape key

### PR DESCRIPTION
**Pull request by dmethvin**
Ref #789

Design pattern and some code taken from examples/requirejs.

### CODE REVIEW

**Comment by samccone** [comment]
code looks nice @dmethvin :) running the tests, thanks for fixing the indentation also :+1:

**Comment by samccone** [comment]
Looks like a tiny style thing @dmethvin 
https://travis-ci.org/tastejs/todomvc/builds/93165358#L1291

**Comment by dmethvin** [comment]
I updated the PR but there seem to be some unrelated issues.

**Comment by samccone** [comment]
yeah it is because this app does not support routing, looks good to me, thanks for this work @dmethvin :clap:

**Pull request merged**
