### PR TITLE
Update Ember to 2.2.0-beta.1

### LINKED ISSUE #1333: Ember DOM node leak
##### Steps  to reproduce

* start timeline profiler
  * add three todos
  * delete three todos
  * (repeat above 2 more times)
* force GC
* stop timeline profiler

screen shot 2015-06-06 at 8 44 03 pm
screen shot 2015-06-06 at 8 43 47 pm

--------

It seems like we are leaking DOM nodes :fountain:

### PR DESCRIPTION
**Pull request by addyosmani**
Attempts to resolve #1333. r/memory leak review: @samccone

### CODE REVIEW

**Comment by samccone** [comment]
I think we will need to vendor the updated lib right? :)

**Comment by addyosmani** [comment]
Whoops. Incoming.

**Comment by samccone** [comment]
heh, looks like stuff might now be totally broken

**Comment by arthurvr** [comment]
If we gotta fix up a bunch of stuff we might as well just try to land https://github.com/tastejs/todomvc/pull/1360 anytime soon. That should fix it too, right?

**Comment by samccone** [comment]
#1360 has a fair bit of work left, for that reason I am OK landing this as an interim solution

**Comment by samccone** [comment]
If i had to guess, it looks like everything might be terribly broken :fire: :bomb:

**Comment by samccone** [comment]
@addyosmani going to close this since @tchak is going to open up a new PR ;) thx :sparkling_heart:

**Pull request closed without merging**
