### PR TITLE
Do not exclude es6 example from lint

### PR DESCRIPTION
**Pull request by samccone**
since 
https://github.com/tastejs/todomvc/pull/1567

We can now handle es6 :)

### CODE REVIEW

**Comment by addyosmani** [comment]
LGTM. Will wait for Travis to finish running.

**Comment by samccone** [comment]
oh this might cause things to fail IRL but not on the CI run (because it does not detect any changes to this example)

**Comment by lukeed** [comment]
Ah, nice. I had ignored it because I had errors left n' right.

**Comment by addyosmani** [comment]
I'm going to land this as-is and see if there's further work we need to do given it's all green otherwise.

**Pull request merged**
