### PR TITLE
📖 Update Current Microsoft Browser to IE11/Edge

### LINKED ISSUE #1785: source map support for vanilla-es6
Hey -

I wanted to add source map support to the vanilla-es6 example.  

I'm able to generate a source map by running the following:

```
npm run compile -- --create_source_map='dist/bundle.js.map' --source_map_format=V3 --output_wrapper=$'%output%\n//# sourceMappingURL=bundle.js.map'
```

However it isn't a working source map (In Chrome or Firefox) and I don't know enough about the closure compiler to get much further.  Wondering if anyone else encountered this and / or wanted to have source maps for this example as well.

screen shot 2017-06-05 at 1 43 22 pm

### LINKED ISSUE #1795: < IE 11 Considered End of Life
Microsoft has sunsetted ALL Internet Explorer projects prior to 11. _**[Please read the End of Life announcement here](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support)**_.

Would be much appreciated to change requirements for submitting a project. There are some projects such as our own that are taking Micro$oft's advice and allowing the web to progress. I feel it removes more modern libraries who only support back to IE11 (As Microsoft suggests) from being able to submit.

https://github.com/devpunks/snuggsi/#browser-support

We are currently preparing for [a new todomvc entry here](https://github.com/devpunks/snuggsi/issues/85) and are not able to submit with the IE9 requirement.

Will submit a Pull Request shortly...

/cc @brandondees @tmornini @halorium

### PR DESCRIPTION
**Pull request by snuggs**
### Relative Issues
Fixes #1795 #autoclose
Addresses https://github.com/devpunks/snuggsi/issues/85
Addresses https://github.com/devpunks/snuggsi/issues/89

### Description
Update current browser for Microsoft Internet Explorer / Edge.

This is due to the announcement early last year 2016 for removal of support from Internet Explorer versions < 11.

capture d ecran 2017-07-07 a 10 11 00

[Read More Here](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support)
And [Here](https://arstechnica.com/information-technology/2017/01/2016-on-the-web-firefox-fights-back-as-microsofts-share-slumps/)

capture d ecran 2017-07-07 a 10 08 13

Would like to submit a todoMVC app but restricted to the most recent browsers which happens to be IE11

Much has changed in the past 12 months. #YaDontKnowWhatYaDontKnow

/cc @brandondees @tmornini @halorium @RobertChristopher @mrbernnz

### CODE REVIEW

**Comment by snuggs** [comment]
### Failure Reason

```bash
    ├── clone@1.0.2 deduped
    ├── clone-stats@0.0.1 deduped
    └── replace-ext@0.0.1 deduped


$ ./test-runner.sh


The command "./test-runner.sh" exited with 1.
store build cache

changes detected, packing new archive
uploading archive


Done. Your build exited with 1.
```

**Comment by snuggs** [comment]
Oh ok am sure you are aware of this. What do we need to do to get the build passing again?
capture d ecran 2017-07-07 a 10 21 32

**Comment by snuggs** [comment]
Wow I thought this would never get merged in. This is awesome!  Now we can do our youtube video explaining todo mvc. @FadySamirSadek if there is anything you'd like our audience in NYC to know about the direction of todo MVC what message can we pass on to the (keyboard) troops?

**Comment by FadySamirSadek** [comment]
@snuggs First of all thank you for your interest in contributing to TodoMVC. The project was not very active for a while as the maintainers were very busy with their day jobs and other stuff. I am now the lead maintainer and will be maintaining the project from now on and will do everything I can to get the project back on track and hopefully make it better and more friendly for new contributors. Regarding the project direction,  I created an issue #1880 explaining everything we are planning to work on in V1.5. For the test suite, we managed to successfully migrate all the test suite from selenium (which was flakey) to cypress and working now to fix the issues that exist in some example so that the build passes again.

**Pull request merged**
