### PR TITLE
Vanilla dart app updates

### PR DESCRIPTION
**Pull request by arthurvr**
* Use npm to manage dependencies, adopt the new UI (#1110)
* Don't suggest to use the deprecated dart editor.
* Fix tests to point to the right directory.
* Update to classes (`todomvc-app-css@2.0`)

### CODE REVIEW

**Comment by samccone** [comment]
@arthurvr so, can you add a .jscsignore and see if you can get this passing locally, when you do an you post the command you ran here so that we can update the linter to respect this file?

**Comment by arthurvr** [comment]
Everything passing now. FYI, there's no such thing as a [`.jscsignore`](https://github.com/jscs-dev/node-jscs/issues/73) file.

**Comment by samccone** [comment]
kk :+1:

**Comment by samccone** [comment]
CI makes this so much easier now :mask: :smile:

**Comment by robbbz** [comment]
Yes thanks for doing that, Sam.

**Pull request merged**
