### PR TITLE
Update marionette version to 2.4.2

### PR DESCRIPTION
**Pull request by dsumac**
Just update

### CODE REVIEW

**Comment by arthurvr** [comment]
Why? We use a caret so the dependency bump isn't needed. Are we running into any concrete issues?

**Comment by addyosmani** [comment]
Same comment as Arthur. I would have thought we would pick up the correct version via caret here.

**Comment by dsumac** [comment]
I have seen this commit 
https://github.com/tastejs/todomvc/commit/9d98ba63bd4a566b42d6a9e1cfaa0528c760b2c1 and I have thought that the strategy was bump the last version. It is a lack of understanding ?
(So, we aren't into an concrete issue.)

**Comment by dsumac** [comment]
About versions, why define backbone dependency (and underscore) in the package.json ?
It's dependencies are defined in the marionette's package.json. Is there a particular purpose to make that ?

**Comment by arthurvr** [comment]
> I have seen this commit 
> 9d98ba6 and I have thought that the strategy was bump the last version. It is a lack of understanding ?

That commit was part of updating some other stuff in the marionette app (https://github.com/tastejs/todomvc/pull/1185). If there are no issues or code changes required there's no point in simply updating dependencies for a patch bump. Doing so would be useless and way too noisy. Thanks for the suggestion though.

> About versions, why define backbone dependency (and underscore) in the package.json ?
> It's dependencies are defined in the marionette's package.json. Is there a particular purpose to make that ?

Because our app explicitly uses those (using `<script>` tags). Besides from that you can't depend on the location of sub-dependencies as npm changed the behaviour of those multiple times in recent versions.

**Comment by dsumac** [comment]
Thanks for the feedback :thumbsup:

**Pull request closed without merging**
