### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by elie29**

### CODE REVIEW

**Comment by samccone** [comment]
I suppose this is better, html escaping vs not 

:+1:

**Comment by arthurvr** [comment]
Will land this together with the other related PRs this evening.

**Comment by elie29** [comment]
Thx :)

**Comment by sindresorhus** [comment]
:+1: but please include a proper commit and PR title.

**Comment by arthurvr** [comment]
https://github.com/tastejs/todomvc/pull/1228#issuecomment-85568559

**Pull request closed without merging**
