### PR TITLE
Backbone example: add id attr to input

### PR DESCRIPTION
**Pull request by cisar**
If `label` has `for` attr, `input` must have `id` with that value.

### CODE REVIEW

**Comment by sindresorhus** [comment]
LGTM

**Comment by boushley** [comment]
:shipit:

**Comment by samccone** [comment]
Woot thanks!!

**Comment by Naylor55** [comment]
Who   are   you  ?
I  am   Chinese，  so   you   can   speak   Chinese?







在 2016-01-04 23:38:48，"Sam Saccone" <notifications@github.com> 写道：


Merged #1574.

**Pull request merged**
