### PR TITLE
Update to polymer 1.2.3

### PR DESCRIPTION
**Pull request by ebidel**
- Update to polymer 1.2.3 (latest)
- using minor (new) perf improvements

### CODE REVIEW

**Comment by samccone** [comment]
Whitespace is sometimes important :) (see failing tests)

Also can you explain for others what this upgrade gets us?

**Comment by ebidel** [comment]
Yea, I had to remove one of them. This one should be good.

**Comment by ebidel** [comment]
> Also can you explain for others what this upgrade gets us? 

See PR description

**Comment by addyosmani** [comment]
Thanks for the update, @ebidel. The PR description appears to be missing. Is the reason that it provides us with a minor performance improvement per https://github.com/Polymer/polymer/issues/2511?

**Pull request merged**
