### PR TITLE
Refactored react-backbone example to break out app and footer into smaller components, and delegate responsibility to those smaller components.

### PR DESCRIPTION
**Pull request by oveddan**
Moved save/destroy/cancel functionality into the todo item
components themselves and out of the app.

Moved filtering of todo items into the collection and out of the app.

Created a TodoList component, which contains the items and keeps track
of which one is currently editing.

Broke out footer into individual components that just grab what they
need from the list, and just modify the list themselves

Also upgrades react to 0.12.1

### CODE REVIEW

**Comment by samccone** [comment]
ping @PascalPrecht

**Comment by chenglou** [comment]
Probably a bit out of date

**Comment by arthurvr** [comment]
This needs a rebase. @passy WDYT about all the above?

**Comment by samccone** [comment]
Going to defer to @chenglou and @passy on their comments about the balance between complexity, abstraction, and readability given the goals of this project.

I am going to close this for now, but if anyone feels strongly and wants to finish this up, please leave your thoughts and we can reopen.

Thanks @oveddan for this work and the discussion.

**Pull request closed without merging**
