### PR TITLE
Updated Ember to 1.10.0-beta.4

### PR DESCRIPTION
**Pull request by ip2k**

### CODE REVIEW

**Comment by ip2k** [comment]
All tests passing:

```
14:53 $ mocha allTests.js --no-timeouts --reporter spec --framework=emberjs


  TodoMVC - emberjs
    When page is initially opened
      ✓ should focus on the todo input field (48ms)
    No Todos
      ✓ should hide #main and #footer (82ms)
    New Todo
      ✓ should allow me to add todo items (548ms)
      ✓ should clear text input field when an item is added (266ms)
      ✓ should append new items to the bottom of the list (628ms)
      ✓ should trim text input (265ms)
      ✓ should show #main and #footer when items added (349ms)
    Mark all as completed
      ✓ should allow me to mark all items as completed (763ms)
      ✓ should allow me to clear the completion state of all items (825ms)
      ✓ complete all checkbox should update state when items are completed / cleared (916ms)
    Item
      ✓ should allow me to mark items as complete (781ms)
      ✓ should allow me to un-mark items as complete (770ms)
      ✓ should allow me to edit an item (975ms)
      ✓ should show the remove button on hover
    Editing
      ✓ should hide other controls when editing (599ms)
      ✓ should save edits on enter (912ms)
      ✓ should save edits on blur (1026ms)
      ✓ should trim entered text (970ms)
      ✓ should remove the item if an empty text string was entered (888ms)
      ✓ should cancel edits on escape (892ms)
    Counter
      ✓ should display the current number of todo items (406ms)
    Clear completed button
      ✓ should display the number of completed items (765ms)
      ✓ should remove completed items when clicked (825ms)
      ✓ should be hidden when there are no items that are completed (740ms)
    Routing
      ✓ should allow me to display active items (811ms)
      ✓ should respect the back button (1286ms)
      ✓ should allow me to display completed items (834ms)
      ✓ should allow me to display all items (1133ms)
      ✓ should highlight the currently applied filter (1405ms)


  29 passing (1m)
```

**Comment by sindresorhus** [comment]
Thanks, but this is a duplicate of #1078 :)

**Comment by ip2k** [comment]
Not quite a duplicate, since this is the newest beta whereas #1078 isn't anymore, but also, how would you feel about a system which automatically tries to update all the examples with a bower.json manifest to the latest versions of those packages / dependencies, then runs all the tests against them and submits a PR automatically if everything passes? I guess this is more a question of confidence in the test suite, but it could help solve the more general problem of keeping all the examples up-to-date.

**Comment by sindresorhus** [comment]
> Not quite a duplicate, since this is the newest beta whereas #1078 isn't anymore

I know. Happy to have this submitted again when #1078 lands if it doesn't already upgrade the deps.

> how would you feel about a system which automatically tries to update all the examples with a bower.json manifest to the latest versions of those packages / dependencies, then runs all the tests against them and submits a PR automatically if everything passes? I guess this is more a question of confidence in the test suite, but it could help solve the more general problem of keeping all the examples up-to-date.

Happy to see the upgrade process more automated, but it should still be triggered manually. Open an issue with your thoughts on how it should be solved ;)

**Comment by phillipsj** [comment]
I finally fixed my branch, but I would go ahead and accept this one since it is more up to date than mine.  Sorry for being so slow.

**Comment by sindresorhus** [comment]
This suffers from the same as @phillipsj, by that it includes a lot of junk files: https://github.com/tastejs/todomvc/pull/1078

Use a .gitignore and only include the needed files for running. See any of the other recent commits for how to do it.

**Comment by addyosmani** [comment]
ping @ip2k

**Comment by samccone** [comment]
Hey @ip2k when you or anyone gets around to addressing the comments left on this please reopen and we can take it from there. Thanks for the work, and hopefully someone can pick this up and push it across the finish line! :racehorse: :checkered_flag:

**Pull request closed without merging**
