### PR TITLE
Add a Git .mailmap with my new name

### PR DESCRIPTION
**Pull request by mgol**
In this way my past contribution is mapped correctly.

### CODE REVIEW

**Comment by mgol** [comment]
`master` is failing, test failures are unrelated to this PR.

**Comment by samccone** [comment]
Is this critical for you? Since github does not support this https://github.com/holman/ama/issues/551, it is only useful for local git clients so I do not see a major win landing this.

Thanks

**Comment by mgol** [comment]
Local Git clients also include IDEs etc. so I find this useful. But it's definitely not critical; I just prefer this data to be correct but if you'd rather not add a new file, I'm fine with not landing this PR.

**Comment by samccone** [comment]
I am find landing it after reflecting more.

Thanks so much for the PR!

**Pull request merged**
