### PR TITLE
Backbone.js - Update app.js

### PR DESCRIPTION
**Pull request by elie29**

### CODE REVIEW

**Comment by samccone** [comment]
hi @elia care to expand on what this is "fixing"?

**Comment by samccone** [comment]
comment pulled from another PR

`https://github.com/elie29/todomvc/commit/6a5ed802d46a453dc19ee840372bd6b4db1511e6`

**Comment by elie29** [comment]
Yes you're right :)

**Comment by sindresorhus** [comment]
:+1: but please include a proper commit and PR title.

**Comment by elie29** [comment]
@samccone Hi, I have add _.debounce to the listening collection for optimisation purpose. How can I merge it with the previous commit?

**Comment by samccone** [comment]
Hi @elia thanks for this work, I am going to close both of your open PRs since they both deal with the same things. Would you mind opening 1 "correct" PR based on our feedback.

Thanks!

**Comment by elia** [comment]
I guess the message was directed to @elie29 ;)

**Pull request closed without merging**
