### PR TITLE
Delegate events to #todo-list instead of document

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by evverx** [comment]
This change inspired from [.live() vs .delegate()](http://www.elijahmanor.com/differences-between-jquery-bind-vs-live-vs-delegate-vs-on/) battle.
`live` cons:
* All your events always delegate all the way up to the document.

@cburgmer , what do you think?

**Comment by passy** [comment]
That looks reasonable to me. Also, shorter!

**Comment by cburgmer** [comment]
Like it!

**Comment by samccone** [comment]
heh :+1:

**Comment by arthurvr** [comment]
I guess this one is good to go? :+1: of mine

**Pull request merged**
