### PR TITLE
Update emberjs example versions

### PR DESCRIPTION
**Pull request by spastorino**
This helps avoiding an infinite PUTs loop when used with the RESTAdapter.

The issue seems to be the same to the one described here ...
http://discuss.emberjs.com/t/save-post-update-put-ember-data-infinite-loop-when-upgrading-to-ember-1-0-0-4-and-ember-data-1-0-0-beta-3/2824

Hat tip @san650

Just in case you want to check the resources I've used ...

http://builds.emberjs.com/release/ember.js
http://builds.emberjs.com/beta/ember-data.js
http://builds.emberjs.com/release/ember-template-compiler.js
http://code.jquery.com/jquery-2.1.4.js

### CODE REVIEW

**Comment by passy** [comment]
Are those just patch release updates to what's specified in the `package.json`, ie. what you get from running `npm update`?

**Comment by spastorino** [comment]
@passy yeah I would do npm update, the thing is the issue is with ember-data, we would need to override that one. Do you want me to run npm update and override ember-data.js?

**Comment by spastorino** [comment]
I've updated the PR reflecting exactly that. Now it's the result of npm update + curl http://builds.emberjs.com/beta/ember-data.js > node_modules/ember-data/ember-data.js

**Comment by passy** [comment]
I'd like to get input from the others, but I'm slightly hesitant to including dependencies that aren't published on npm yet.

**Comment by arthurvr** [comment]
> I'd like to get input from the others, but I'm slightly hesitant to including dependencies that aren't published on npm yet.

Yep, we should try to push them to publishing it instead.

**Comment by spastorino** [comment]
I mainly updated ember-data because it's there anyway, and the one there has bugs.
But as you guys wish.

**Comment by spastorino** [comment]
A bit more context ember-data was added here https://github.com/tastejs/todomvc/commit/26d239c2cd7e7333dfeafcceac1306f80036f412 before it was being installed using bower.

/cc @tomdale @wycats

**Comment by tomdale** [comment]
We have plans to distribute Ember Data on npm but for now the official distribution channel is Bower. I'll reiterate that I think the best way to give people a taste of Ember is to use Ember CLI to build the app (https://github.com/tastejs/todomvc/issues/1069#issuecomment-63800583); the whole point of Ember is that it's a complete front-end stack and abstracts away painful dependency management stuff like this.

**Comment by wycats** [comment]
I agree with @tomdale

**Comment by passy** [comment]
I'd be in favor of migrating the example to ember-cli if it represents the
best practices for Ember development. Comparability isn't really meaningful
if the app would not actually be built that way.

What do the others think?

**Comment by addyosmani** [comment]
I agree with @passy. If the idiomatic way to build all Ember apps is using ember-cli, then I'm in favour of us migrating the app in that direction.

**Comment by tomdale** [comment]
@addyosmani That's awesome, do you want me to try to rustle up some community members to help out with this? I'm not sure where to get started.

**Comment by addyosmani** [comment]
@tomdale That would be incredibly helpful. One option would be to do a fresh implementation following our spec using ember-cli, using the current implementation of the Ember app for inspiration as needed. We can help with reviews/guidance for spec compliance. Love to see this through!

**Comment by arthurvr** [comment]
Over at https://github.com/tastejs/todomvc/issues/1069 some community members already showed their interest in building something up too.

**Comment by spastorino** [comment]
What about this repo https://github.com/ember-cli/ember-cli-todos and/or asking these people for help? /cc @tomdale @wycats

**Comment by arthurvr** [comment]
There was an Ember CLI example submitted: #1360. Let's close this PR in favor of that one.

**Pull request closed without merging**
