### PR TITLE
✋ bye sauce hello travis

### PR DESCRIPTION
**Pull request by samccone**
After lots of work I have found a way for us to run chrome on travis!!!!

no more sauce, all PRs remote or local will run integration tests, this is awesome!

:dancer: :dancers: :beers: :tada: :balloon:

### CODE REVIEW

**Comment by samccone** [comment]
ok: https://travis-ci.org/tastejs/todomvc/builds/69982791#L685

works like a champ ^ looks like it caught a bug in the angular implementation :dancer:

**Comment by sindresorhus** [comment]
Awesome! :fireworks: 

-

Write a blog post!

**Comment by samccone** [comment]
> Write a blog post!

**Comment by arthurvr** [comment]
Cool!

**Comment by stephanebachelier** [comment]
@samccone really awesome!

**Pull request merged**
