### PR TITLE
🍕🌟Polymer 1.0 🌟🍕

### PR DESCRIPTION
**Pull request by samccone**
welp here it is the 1.0 move, there are quite a few things in this upgrade that I am not too happy with however I will ping some people for some input.

-------

I am not going to the the ~~UI or~~ ID migration in this PR that will be after

------

~~CI Will be green soonish. The initial implementation was never compliment so I'm working on it~~

CI is :green_apple: ~~on every planet except for CI 😭 investigating~~

### CODE REVIEW

**Comment by arthurvr** [comment]
Ref gh-1342

**Comment by arthurvr** [comment]
Does this also fix https://github.com/tastejs/todomvc/issues/1257?

**Comment by samccone** [comment]
friendly ping @addyosmani :wink:

**Comment by addyosmani** [comment]
Reviewing today!

**Comment by addyosmani** [comment]
There are a few places here where you're qSA'ing against elements inside a `dom-module` rather than using the `this.$.<ID of thing>`.  I understand doing this for nested elements but where it's not deeply nested, is there a reason for that preference? :lollipop:

**Comment by samccone** [comment]
re:
> qSA'ing against elements inside a dom-module

 oh so when an element is within a `dom-if` it looks like the this.$. never picks up / caches the element :( That is why I am doing it that way :smile:

**Comment by addyosmani** [comment]
Changes here now LGTM. Nice work, @samccone! :cake: :cupid:

**Comment by samccone** [comment]
:+1: :tada: :boom:

**Pull request merged**
