### PR TITLE
Migrates Ember app to new UI :truck:

### PR DESCRIPTION
**Pull request by Gargol**
refs #1110

- upgrade to new UI
- didn't migrate to npm as they are not hosted there in ember's case
- fixed a little bug on 'Clear completed' button as it wa missplaced with new styles

### CODE REVIEW

**Comment by Gargol** [comment]
btw, was running browser tests and it seems like these are failing:

```
Clear completed button
  1) should display the number of completed items
  2) should remove completed items when clicked
  3) should be hidden when there are no items that are completed
```
I guess, they will be updated whenever all the apps are migrated to new UI.

**Comment by sindresorhus** [comment]
> didn't migrate to npm as they are not hosted there in ember's case

`ember-data` and `ember-localstorage-adapter` is on npm. As for `ember` you can still reference it using the git repo.

```json
{
  "ember": "emberjs/ember.js#v1.10.0-beta.4"
}
```

-

Would you mind opening a ticket on Ember about keeping the npm `ember` package up to date?

**Comment by arthurvr** [comment]
> Would you mind opening a ticket on Ember about keeping the npm ember package up to date?

@sindresorhus There already is: https://github.com/emberjs/ember.js/issues/9354.

**Comment by Gargol** [comment]
tried updating to npm, but it seems like having an ember repo wont help much as they don't have actual `ember.js` file in their source it is generated and then pushed to different distribution channels. should we stay with bower or have regular `ember.js` file commited ?

**Comment by sindresorhus** [comment]
@Gargol Actually, they have this for the dist: https://github.com/components/ember/blob/master/package.json

**Comment by Gargol** [comment]
sorry guys, having hard time figuring this out. tried doing it with this config:
```json
{
  "private": true,
  "dependencies": {
    "todomvc-app-css": "^1.0.0",
    "todomvc-common": "^1.0.1",
    "jquery": "^2.1.0",
    "handlebars": "^2.0.0",
    "ember": "components/ember#1.10.0-beta.3",
    "ember-data": "components/ember-data#1.0.0-beta.14.1",
    "ember-localstorage-adapter": "^0.5.0"
  }
}
```
Although, the ember repo is fetched just fine, there is an error when npm is trying to resolve dependencies for `ember-data` , this is what I get in the console: 
```
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/home/gargol/.nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v2.1.14
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: ember@'>=1.8.1 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.9.7-1","0.9.8","0.9.8-1","1.0.0-pre","1.0.0-pre.m1","1.0.0-pre.m2","1.0.0-pre.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
Any suggestions how this could be solved ?

**Comment by sindresorhus** [comment]
@Gargol Ugh, what a mess. Let's just include `ember-data` manually for now.

-

@tomdale fyi.

**Comment by Gargol** [comment]
@sindresorhus updated PR with `npm` integration, left `ember-data` as a stand alone file that is not managed by `npm` for now.

**Comment by sindresorhus** [comment]
@Gargol You have to include the files needed for running.

**Comment by Gargol** [comment]
@sindresorhus should be ok now

**Comment by sindresorhus** [comment]
Thank you @Gargol :)

**Comment by Gargol** [comment]
@sindresorhus happy to help out any time :tada:

**Comment by addyosmani** [comment]
:+1:

**Comment by tomdale** [comment]
Ugh, that is a mess. Sorry for all the trouble. Is it possible to move the Ember example to Ember CLI? That would probably give people a better taste of the framework anyway, and all the bundling of dependencies is handled.

**Comment by sindresorhus** [comment]
@tomdale https://github.com/tastejs/todomvc/issues/1069#issuecomment-63800583

**Pull request closed without merging**
