### PR TITLE
React: Remove direct DOM manipulation

### PR DESCRIPTION
**Pull request by passy**
Turn the `<input>` into a
[Controlled Component](https://facebook.github.io/react/docs/forms.html#controlled-components)
and avoid fiddling with the DOM in an imperative way.

[Review on Reviewable](https://reviewable.io/reviews/tastejs/todomvc/1481)

### CODE REVIEW

**Comment by samccone** [comment]
:+1: this is much better :)

**Comment by samccone** [comment]
@passy looks like the failure is due to one of our child dependencies starting to use es6

The easy fix might be just to bump our travis.yaml to 4
https://github.com/tastejs/todomvc/blob/master/.travis.yml#L8

**Comment by sindresorhus** [comment]
> The easy fix might be just to bump our travis.yaml to node 4

Yeah, no reason not to use the latest Node.js there. I would go with `'stable'` so we don't have to update it for every Node.js version.

**Comment by samccone** [comment]
just a rebase on this @passy and tests should actually run now :penguin:

**Comment by passy** [comment]
Rebased. Now fingers crossed! :v:

**Pull request merged**
