### PR TITLE
Add Vue to update folder

### PR DESCRIPTION
**Pull request by flashdesignory**
This version has been lifted from Speedometer and follows the WebKit styles guide.

For more context regarding this update, please view https://github.com/tastejs/todomvc/issues/2199.

@kara

### CODE REVIEW

**Comment by FadySamirSadek** [comment]
@momostafas can you help reviewing this?

**Comment by FadySamirSadek** [comment]
@flashdesignory Can we get someone from the Vue team to review this?

**Comment by flashdesignory** [comment]
Thanks @yyx990803 for the quick review. 
I'll take a look and make the suggested updates.

**Comment by flashdesignory** [comment]
@yyx990803 @FadySamirSadek - closing this pr in favor of https://github.com/tastejs/todomvc/pull/2213

**Pull request closed without merging**
