### PR TITLE
Angularjs-perf update: change to minified Angular and renaming

### PR DESCRIPTION
**Pull request by dmitriz**
- Switched to minified Angular, urgently needed due to
  https://github.com/tastejs/todomvc/issues/1575, in line with https://github.com/tastejs/todomvc/issues/1541 and https://github.com/tastejs/todomvc/issues/1572
- Changed `TC` to `tC` to address comment https://github.com/tastejs/todomvc/pull/1561#discussion-diff-48415192 by  @IgorMinar
- Update to the most recent Angular 1.4.8

### CODE REVIEW

**Comment by samccone** [comment]
imho we should "kill" angular-perf and move this implementation into

`https://github.com/tastejs/todomvc/tree/master/examples/angularjs/perf`

We can just use a meta redirect refresh in this folder so we do not break any old links....


ref #1541

thoughts @tastejs/todomvc ?

**Comment by passy** [comment]
@samccone :+1: It's confusing to have it as a separate item in the menu.

**Comment by addyosmani** [comment]
>  It's confusing to have it as a separate item in the list on the homepage.

:+1: Let's move it.

**Comment by IgorMinar** [comment]
Let's just delete it. With Angular 2 in beta it's not necessary to have
this perf version anymore since A2 is much faster.

**Comment by addyosmani** [comment]
@samccone @passy if we decide to drop the example, here's a PR: https://github.com/tastejs/todomvc/pull/1586

**Comment by arthurvr** [comment]
Can we take another look at this and fix the merge conflicts? :)

**Comment by dmitriz** [comment]
Sure, if there a chance of getting it accepted ;)
Also with A 1.5 out, we can refine it to a more modern component based feel?

I see Angular 1 as playing an important niche role for people who need something better than jQuery but are not prepared to invest in massive tooling required for more advanced frameworks. The "perf" here is also related to the code simplicity the ways I see, perhaps that can be better advertised?

**Comment by addyosmani** [comment]
Friendly ping @dmitriz :)

**Comment by dmitriz** [comment]
@addyosmani I am somewhat puzzled by no comments to my questions, so I am not sure what is expected.

Is there a guarantee that this PR will actually be merged if fixed? And if yes, how soon? 

No comments at all?

And none to this? -
https://github.com/tastejs/todomvc/issues/1566

**Pull request closed without merging**
