### PR TITLE
Sjs/update agility app ui

### PR DESCRIPTION
**Pull request by samccone**
This project does not have a package.json and has not been active since
June 1 2013, so instead of waiting for a package.json to be merged I
choose to use a project called napa to allow for installs of packages
without a package.json

-------

Via #1110

### CODE REVIEW

**Comment by sindresorhus** [comment]
> This project does not have a package.json and has not been active since June 1 2013

Oh wow. That's a pretty good sign we should remove it from TodoMVC altogether. We can put a link to your version in the wiki. @tastejs/todomvc thoughts?

**Comment by samccone** [comment]
After all my work :( bahahahah

**Comment by samccone** [comment]
but yes :+1: to remove

**Comment by sindresorhus** [comment]
@samccone Yeah, sorry about that. I had no idea idea it was that dead... But we're not doing our users any favor of having it there when the project is dead.

**Comment by addyosmani** [comment]
:+1: to removing but thanks for working on this @samccone. My vote is to link to this from our wiki.

**Comment by sindresorhus** [comment]
@samccone Can you update the wiki entry to point to your fork?

https://github.com/tastejs/todomvc/wiki/Other-implementations#agility-unmaintained

**Pull request closed without merging**
