### PR TITLE
Nodoka00 (Josh Johnson) making a pull request for his coding exercise

### PR DESCRIPTION
**Pull request by ChitoseHibiya**
The majority of the commits are for tests/Nodoka00_conf.js and _spec.js, but there are a few that are tagged elsewhere, since they deal with Bower dependencies.

To clarify the relevant commits, here is a brief list:

1) Simple configuration changes
2) Pending tests
3) ~ 11) Actual tests
12) Finalizing tests (no iit's, so that all tests run in order)

### CODE REVIEW

**Comment by samccone** [comment]
@ChitoseHibiya I am a bit lost as to the goal of this PR. Can you explain what is the goal of this PR? What does it add to the project.

Thanks!

**Comment by jj4th** [comment]
@samccone This is part of a coding test.  @ChitoseHibiya was instructed to raise their PR against their own fork, and failed at this task, feel free to close this PR.

**Comment by samccone** [comment]
best of luck @ChitoseHibiya !

**Comment by jj4th** [comment]
Apologies, we have restructured our code test process so that this should not happen again.

**Comment by samccone** [comment]
no worries @jj4th cool to see this use of todomvc

**Pull request closed without merging**
