### PR TITLE
Fix link to template on homepage.

### PR DESCRIPTION
**Pull request by KenPowers**
The link to the app template on the homepage is broken.

### CODE REVIEW

**Comment by arthurvr** [comment]
Yep, LGTM!

**Comment by KenPowers** [comment]
:shipit:?

**Comment by addyosmani** [comment]
Can we get this rebased against master?

**Comment by KenPowers** [comment]
Done though it looks like the link was already fixed in the mean time.

**Comment by arthurvr** [comment]
Yes, https://github.com/tastejs/todomvc/pull/1177 was duplicate of this one.

**Pull request closed without merging**
