### PR TITLE
Update `knockoutjs_require` to new app UI

### PR DESCRIPTION
**Pull request by andreruffert**
> #1110

### CODE REVIEW

**Comment by sindresorhus** [comment]
Same issue as https://github.com/tastejs/todomvc/pull/1156#issuecomment-73849589

**Comment by andreruffert** [comment]
Damnit! :grin:
The `Clear completed` button position issue is fixed with d1b5a65.

Btw. I've spotted another issue in general. The `Clear completed` button has no completed count anymore (it's not visible).

_before new app UI:_
bildschirmfoto 2015-02-11 um 14 45 17

_after new app UI:_
bildschirmfoto 2015-02-11 um 14 50 43

Should I open an issue for this?

**Comment by sindresorhus** [comment]
> Btw. I've spotted another issue in general. The Clear completed button has no completed count anymore (it's not visible).

That's intentional.

**Comment by andreruffert** [comment]
Alrighty! All the better :relaxed:

**Pull request closed without merging**
