### PR TITLE
Update to Ember 2.10 and use HashLocation

### PR DESCRIPTION
**Pull request by cibernox**
This will (I think) fix the broken link to the EmberJS version.

It also updates to the version of the framework to 2.10

### CODE REVIEW

**Comment by cibernox** [comment]
Is there a way of skipping style checking on the minified code?

**Comment by cibernox** [comment]
Nevermind, I found it. There is an error in the tastejs example now 😕

**Comment by addyosmani** [comment]
> There is an error in the tastejs example now 

Which example are you referring to? The one in this PR or another one you're referencing?

**Comment by addyosmani** [comment]
Fyi, restarted the Travis CI build as it wasn't able to complete due to a WebDriver issue last time.

**Comment by cibernox** [comment]
@addyosmani I see my confusion now. I thought that `tastejs` was the name of some niche JS framework 😅 

Same web driver error tho.

**Comment by addyosmani** [comment]
Haven't been able to fix the web driver issue but we may end up landing & iterating on this as the current version hosted is busted.

**Comment by cibernox** [comment]
Feel free to merge then. I guess I'll PR a version with 2.11 very soon.

**Comment by timhaines** [comment]
@cibernox @addyosmani Sounds great guys.  I'd like to send in a PR adding a simple integration test to the ember app.  To keep things simple perhaps I'll do it after this one lands?

**Comment by cibernox** [comment]
I think so. Besides, I think that 2.11 will land today. You could add that integration test and update in the same PR.

**Comment by addyosmani** [comment]
Sounds great, @timhaines!

**Pull request merged**
