### PR TITLE
Update `typescript-backbone` to new app UI

### PR DESCRIPTION
**Pull request by andreruffert**
> #1110

Refactor(additional): move `backbone.localstorage.js` to npm 9d5bb45

### CODE REVIEW

**Comment by sindresorhus** [comment]
The `Clear completed` button is in the wrong position. (mark a todo a completed). There is probably needless whitespace around the text inside it.

**Comment by arthurvr** [comment]
Oh, btw, @andreruffert, great work!

**Comment by andreruffert** [comment]
WTF sorry the `squash` went wrong... I'll open an new pr for this!

**Comment by sindresorhus** [comment]
In the future you can just force push a fixed local branch to the remote PR branch to fix any issue without opening a new PR ;)

**Comment by andreruffert** [comment]
Yep thanks! I'll try this next time :)

**Pull request closed without merging**
